<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXXAK4c3\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXXAK4c3/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerXXAK4c3.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerXXAK4c3\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerXXAK4c3\App_KernelProdContainer([
    'container.build_hash' => 'XXAK4c3',
    'container.build_id' => '51a28b90',
    'container.build_time' => 1786438989,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXXAK4c3');
