<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QxxAWndService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.QxxAWnd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QxxAWnd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'story' => ['privates', '.errored..service_locator.QxxAWnd.App\\Entity\\Story', NULL, 'Cannot autowire service ".service_locator.QxxAWnd": it references class "App\\Entity\\Story" but no such service exists.'],
        ], [
            'em' => '?',
            'story' => 'App\\Entity\\Story',
        ]);
    }
}
