<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8ZciZHService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.8ZciZ_H' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8ZciZ_H'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'promoReseau' => ['privates', '.errored..service_locator.8ZciZ_H.App\\Entity\\PromoReseau', NULL, 'Cannot autowire service ".service_locator.8ZciZ_H": it references class "App\\Entity\\PromoReseau" but no such service exists.'],
            'zefame' => ['privates', 'App\\Utilities\\ZefameApi', 'getZefameApiService', true],
        ], [
            'em' => '?',
            'promoReseau' => 'App\\Entity\\PromoReseau',
            'zefame' => 'App\\Utilities\\ZefameApi',
        ]);
    }
}
