<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5MMoGl2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.5MMoGl2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5MMoGl2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'logRepo' => ['privates', 'App\\Repository\\LogBoiteMailRepository', 'getLogBoiteMailRepositoryService', true],
        ], [
            'logRepo' => 'App\\Repository\\LogBoiteMailRepository',
        ]);
    }
}
