<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Mu24nTqService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Mu24nTq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Mu24nTq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'tuto' => ['privates', '.errored..service_locator.Mu24nTq.App\\Entity\\Tuto', NULL, 'Cannot autowire service ".service_locator.Mu24nTq": it references class "App\\Entity\\Tuto" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'tuto' => 'App\\Entity\\Tuto',
        ]);
    }
}
