<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BpVnoLMService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.BpVnoLM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BpVnoLM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'formulePromoAffaireRepository' => ['privates', 'App\\Repository\\FormulePromoAffaireRepository', 'getFormulePromoAffaireRepositoryService', true],
            'sessionDS' => ['privates', 'App\\Services\\SessionDS', 'getSessionDSService', true],
            'traitementsDS' => ['services', 'App\\Services\\TraitementsDS', 'getTraitementsDSService', true],
        ], [
            'formulePromoAffaireRepository' => 'App\\Repository\\FormulePromoAffaireRepository',
            'sessionDS' => 'App\\Services\\SessionDS',
            'traitementsDS' => 'App\\Services\\TraitementsDS',
        ]);
    }
}
