<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3PHq_PiService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.3PHq.pi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3PHq.pi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'transaction' => ['privates', '.errored..service_locator.3PHq.pi.App\\Entity\\Transaction', NULL, 'Cannot autowire service ".service_locator.3PHq.pi": it references class "App\\Entity\\Transaction" but no such service exists.'],
        ], [
            'transaction' => 'App\\Entity\\Transaction',
        ]);
    }
}
