<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S1898X9Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.s1898X9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.s1898X9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'myTransaction' => ['privates', '.errored..service_locator.s1898X9.App\\Entity\\Transaction', NULL, 'Cannot autowire service ".service_locator.s1898X9": it references class "App\\Entity\\Transaction" but no such service exists.'],
            'user' => ['privates', '.errored..service_locator.s1898X9.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.s1898X9": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'myTransaction' => 'App\\Entity\\Transaction',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
