<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JeDCUF5Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.JeDCUF5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JeDCUF5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'story' => ['privates', '.errored..service_locator.JeDCUF5.App\\Entity\\Story', NULL, 'Cannot autowire service ".service_locator.JeDCUF5": it references class "App\\Entity\\Story" but no such service exists.'],
        ], [
            'story' => 'App\\Entity\\Story',
        ]);
    }
}
