<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZlEHvaEService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.zlEHvaE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zlEHvaE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'prospect' => ['privates', '.errored..service_locator.zlEHvaE.App\\Entity\\MailProspect', NULL, 'Cannot autowire service ".service_locator.zlEHvaE": it references class "App\\Entity\\MailProspect" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'prospect' => 'App\\Entity\\MailProspect',
        ]);
    }
}
