<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VyjfBdcService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.VyjfBdc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VyjfBdc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'boostRepository' => ['privates', 'App\\Repository\\BoostRepository', 'getBoostRepositoryService', true],
            'formulePromoAffaireRepository' => ['privates', 'App\\Repository\\FormulePromoAffaireRepository', 'getFormulePromoAffaireRepositoryService', true],
            'methodePaiementRepository' => ['privates', 'App\\Repository\\MethodePaiementRepository', 'getMethodePaiementRepositoryService', true],
            'promotionRepository' => ['privates', 'App\\Repository\\PromotionRepository', 'getPromotionRepositoryService', true],
            'traitementsDS' => ['services', 'App\\Services\\TraitementsDS', 'getTraitementsDSService', true],
            'verificationsDS' => ['services', 'App\\Services\\VerificationsDS', 'getVerificationsDSService', true],
        ], [
            'boostRepository' => 'App\\Repository\\BoostRepository',
            'formulePromoAffaireRepository' => 'App\\Repository\\FormulePromoAffaireRepository',
            'methodePaiementRepository' => 'App\\Repository\\MethodePaiementRepository',
            'promotionRepository' => 'App\\Repository\\PromotionRepository',
            'traitementsDS' => 'App\\Services\\TraitementsDS',
            'verificationsDS' => 'App\\Services\\VerificationsDS',
        ]);
    }
}
