<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3COxMsJService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.3COxMsJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3COxMsJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'preuve' => ['privates', '.errored..service_locator.3COxMsJ.App\\Entity\\Preuve', NULL, 'Cannot autowire service ".service_locator.3COxMsJ": it references class "App\\Entity\\Preuve" but no such service exists.'],
            'traitementsDS' => ['services', 'App\\Services\\TraitementsDS', 'getTraitementsDSService', true],
        ], [
            'em' => '?',
            'preuve' => 'App\\Entity\\Preuve',
            'traitementsDS' => 'App\\Services\\TraitementsDS',
        ]);
    }
}
