<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VYUlMjCService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.VYUlMjC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VYUlMjC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'formuleBoost' => ['privates', '.errored..service_locator.VYUlMjC.App\\Entity\\FormuleBoost', NULL, 'Cannot autowire service ".service_locator.VYUlMjC": it references class "App\\Entity\\FormuleBoost" but no such service exists.'],
        ], [
            'formuleBoost' => 'App\\Entity\\FormuleBoost',
        ]);
    }
}
