<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WnCsyP9Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.wnCsyP9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wnCsyP9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'boostRepository' => ['privates', 'App\\Repository\\BoostRepository', 'getBoostRepositoryService', true],
            'promoReseauRepository' => ['privates', 'App\\Repository\\PromoReseauRepository', 'getPromoReseauRepositoryService', true],
            'promotionRepository' => ['privates', 'App\\Repository\\PromotionRepository', 'getPromotionRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'boostRepository' => 'App\\Repository\\BoostRepository',
            'promoReseauRepository' => 'App\\Repository\\PromoReseauRepository',
            'promotionRepository' => 'App\\Repository\\PromotionRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
