<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Dhg828pService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Dhg828p' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Dhg828p'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'transaction' => ['privates', '.errored..service_locator.Dhg828p.App\\Entity\\Transaction', NULL, 'Cannot autowire service ".service_locator.Dhg828p": it references class "App\\Entity\\Transaction" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'transaction' => 'App\\Entity\\Transaction',
        ]);
    }
}
