<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ATyPcYbService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.ATyPcYb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ATyPcYb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'deletedD' => ['privates', '.errored..service_locator.ATyPcYb.App\\Entity\\DeletedDS', NULL, 'Cannot autowire service ".service_locator.ATyPcYb": it references class "App\\Entity\\DeletedDS" but no such service exists.'],
        ], [
            'deletedD' => 'App\\Entity\\DeletedDS',
        ]);
    }
}
