<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CsgaVOCService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.csgaVOC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.csgaVOC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'historiqueRepo' => ['privates', 'App\\Repository\\HistoriqueProgrammeRecompenseRepository', 'getHistoriqueProgrammeRecompenseRepositoryService', true],
            'promotion' => ['privates', '.errored..service_locator.csgaVOC.App\\Entity\\Promotion', NULL, 'Cannot autowire service ".service_locator.csgaVOC": it references class "App\\Entity\\Promotion" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'historiqueRepo' => 'App\\Repository\\HistoriqueProgrammeRecompenseRepository',
            'promotion' => 'App\\Entity\\Promotion',
        ]);
    }
}
