<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T8TFfbTService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.T8TFfbT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.T8TFfbT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'formulePromoAffaire' => ['privates', '.errored..service_locator.T8TFfbT.App\\Entity\\FormulePromoAffaire', NULL, 'Cannot autowire service ".service_locator.T8TFfbT": it references class "App\\Entity\\FormulePromoAffaire" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'formulePromoAffaire' => 'App\\Entity\\FormulePromoAffaire',
        ]);
    }
}
