<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CyurbgxService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Cyurbgx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Cyurbgx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'formulePromoReseau' => ['privates', '.errored..service_locator.Cyurbgx.App\\Entity\\FormulePromoReseau', NULL, 'Cannot autowire service ".service_locator.Cyurbgx": it references class "App\\Entity\\FormulePromoReseau" but no such service exists.'],
        ], [
            'formulePromoReseau' => 'App\\Entity\\FormulePromoReseau',
        ]);
    }
}
