<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KY1HarjService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.KY1Harj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KY1Harj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'suggestion' => ['privates', '.errored..service_locator.KY1Harj.App\\Entity\\Suggestion', NULL, 'Cannot autowire service ".service_locator.KY1Harj": it references class "App\\Entity\\Suggestion" but no such service exists.'],
        ], [
            'suggestion' => 'App\\Entity\\Suggestion',
        ]);
    }
}
