<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5RM4gVService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.5RM_4gV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5RM_4gV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'traitementsDS' => ['services', 'App\\Services\\TraitementsDS', 'getTraitementsDSService', true],
            'user' => ['privates', '.errored..service_locator.5RM_4gV.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.5RM_4gV": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'traitementsDS' => 'App\\Services\\TraitementsDS',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
