<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Wx0ziklService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Wx0zikl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Wx0zikl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entity' => ['privates', '.errored..service_locator.Wx0zikl.App\\Entity\\HistoriqueProgrammeRecompense', NULL, 'Cannot autowire service ".service_locator.Wx0zikl": it references class "App\\Entity\\HistoriqueProgrammeRecompense" but no such service exists.'],
        ], [
            'entity' => 'App\\Entity\\HistoriqueProgrammeRecompense',
        ]);
    }
}
