<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_L4W48Z2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.L4W48Z2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.L4W48Z2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'formulePromoReseau' => ['privates', '.errored..service_locator.L4W48Z2.App\\Entity\\FormulePromoReseau', NULL, 'Cannot autowire service ".service_locator.L4W48Z2": it references class "App\\Entity\\FormulePromoReseau" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'formulePromoReseau' => 'App\\Entity\\FormulePromoReseau',
        ]);
    }
}
