<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IGGPIQFService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.IGGPIQF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IGGPIQF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'formulePromoAffaire' => ['privates', '.errored..service_locator.IGGPIQF.App\\Entity\\FormulePromoAffaire', NULL, 'Cannot autowire service ".service_locator.IGGPIQF": it references class "App\\Entity\\FormulePromoAffaire" but no such service exists.'],
        ], [
            'formulePromoAffaire' => 'App\\Entity\\FormulePromoAffaire',
        ]);
    }
}
