<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I8TJNVAService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.I8TJNVA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.I8TJNVA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'methodePaiementRepository' => ['privates', 'App\\Repository\\MethodePaiementRepository', 'getMethodePaiementRepositoryService', true],
        ], [
            'methodePaiementRepository' => 'App\\Repository\\MethodePaiementRepository',
        ]);
    }
}
