<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NnoD9VBService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.NnoD9VB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NnoD9VB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'historiqueProgrammeRecompenseRepository' => ['privates', 'App\\Repository\\HistoriqueProgrammeRecompenseRepository', 'getHistoriqueProgrammeRecompenseRepositoryService', true],
            'promotionRepository' => ['privates', 'App\\Repository\\PromotionRepository', 'getPromotionRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'em' => '?',
            'historiqueProgrammeRecompenseRepository' => 'App\\Repository\\HistoriqueProgrammeRecompenseRepository',
            'promotionRepository' => 'App\\Repository\\PromotionRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
