<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Mmc86ZcService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.mmc86Zc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mmc86Zc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mailProspectRepository' => ['privates', 'App\\Repository\\MailProspectRepository', 'getMailProspectRepositoryService', true],
        ], [
            'mailProspectRepository' => 'App\\Repository\\MailProspectRepository',
        ]);
    }
}
