<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BCFeMf3Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.BCFeMf3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BCFeMf3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entity' => ['privates', '.errored..service_locator.BCFeMf3.App\\Entity\\HistoriqueProgrammeRecompense', NULL, 'Cannot autowire service ".service_locator.BCFeMf3": it references class "App\\Entity\\HistoriqueProgrammeRecompense" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'entity' => 'App\\Entity\\HistoriqueProgrammeRecompense',
            'entityManager' => '?',
        ]);
    }
}
