<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GFkPXpWService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.GFkPXpW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GFkPXpW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'formuleDressurBot' => ['privates', '.errored..service_locator.GFkPXpW.App\\Entity\\FormuleDressurBot', NULL, 'Cannot autowire service ".service_locator.GFkPXpW": it references class "App\\Entity\\FormuleDressurBot" but no such service exists.'],
        ], [
            'formuleDressurBot' => 'App\\Entity\\FormuleDressurBot',
        ]);
    }
}
