<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ex3Dn57Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Ex3Dn57' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ex3Dn57'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
            'story' => ['privates', '.errored..service_locator.Ex3Dn57.App\\Entity\\Story', NULL, 'Cannot autowire service ".service_locator.Ex3Dn57": it references class "App\\Entity\\Story" but no such service exists.'],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'em' => '?',
            'slugger' => '?',
            'story' => 'App\\Entity\\Story',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
