<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MBK214Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.mB_k214' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mB_k214'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'sessionDS' => ['privates', 'App\\Services\\SessionDS', 'getSessionDSService', true],
            'traitementsDS' => ['services', 'App\\Services\\TraitementsDS', 'getTraitementsDSService', true],
        ], [
            'sessionDS' => 'App\\Services\\SessionDS',
            'traitementsDS' => 'App\\Services\\TraitementsDS',
        ]);
    }
}
