<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5C_U1bService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.5C_.u1b' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5C_.u1b'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'envMailSenderRepository' => ['privates', 'App\\Repository\\EnvMailSenderRepository', 'getEnvMailSenderRepositoryService', true],
        ], [
            'entityManager' => '?',
            'envMailSenderRepository' => 'App\\Repository\\EnvMailSenderRepository',
        ]);
    }
}
