<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DGSuVaWService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.DGSuVaW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DGSuVaW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'boostRepository' => ['privates', 'App\\Repository\\BoostRepository', 'getBoostRepositoryService', true],
            'formuleBoostRepository' => ['privates', 'App\\Repository\\FormuleBoostRepository', 'getFormuleBoostRepositoryService', true],
            'formuleDressurBotRepository' => ['privates', 'App\\Repository\\FormuleDressurBotRepository', 'getFormuleDressurBotRepositoryService', true],
            'methodePaiementRepository' => ['privates', 'App\\Repository\\MethodePaiementRepository', 'getMethodePaiementRepositoryService', true],
            'promotionRepository' => ['privates', 'App\\Repository\\PromotionRepository', 'getPromotionRepositoryService', true],
            'traitementsDS' => ['services', 'App\\Services\\TraitementsDS', 'getTraitementsDSService', true],
            'userBotRepository' => ['privates', 'App\\Repository\\UserBotRepository', 'getUserBotRepositoryService', true],
            'verificationsDS' => ['services', 'App\\Services\\VerificationsDS', 'getVerificationsDSService', true],
        ], [
            'boostRepository' => 'App\\Repository\\BoostRepository',
            'formuleBoostRepository' => 'App\\Repository\\FormuleBoostRepository',
            'formuleDressurBotRepository' => 'App\\Repository\\FormuleDressurBotRepository',
            'methodePaiementRepository' => 'App\\Repository\\MethodePaiementRepository',
            'promotionRepository' => 'App\\Repository\\PromotionRepository',
            'traitementsDS' => 'App\\Services\\TraitementsDS',
            'userBotRepository' => 'App\\Repository\\UserBotRepository',
            'verificationsDS' => 'App\\Services\\VerificationsDS',
        ]);
    }
}
