<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZFOho_IService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.ZFOho.I' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZFOho.I'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'userBot' => ['privates', '.errored..service_locator.ZFOho.I.App\\Entity\\UserBot', NULL, 'Cannot autowire service ".service_locator.ZFOho.I": it references class "App\\Entity\\UserBot" but no such service exists.'],
        ], [
            'userBot' => 'App\\Entity\\UserBot',
        ]);
    }
}
