<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZfGfVBfService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.ZfGfVBf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZfGfVBf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'envPaiementApi' => ['privates', '.errored..service_locator.ZfGfVBf.App\\Entity\\EnvPaiementApi', NULL, 'Cannot autowire service ".service_locator.ZfGfVBf": it references class "App\\Entity\\EnvPaiementApi" but no such service exists.'],
        ], [
            'envPaiementApi' => 'App\\Entity\\EnvPaiementApi',
        ]);
    }
}
