<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Sgxr3_ZService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Sgxr3.z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Sgxr3.z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'preuve' => ['privates', '.errored..service_locator.Sgxr3.z.App\\Entity\\Preuve', NULL, 'Cannot autowire service ".service_locator.Sgxr3.z": it references class "App\\Entity\\Preuve" but no such service exists.'],
        ], [
            'preuve' => 'App\\Entity\\Preuve',
        ]);
    }
}
