<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O8chO8AService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.o8chO8A' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.o8chO8A'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'fileAttenteRepo' => ['privates', 'App\\Repository\\FileAttenteProspectMailRepository', 'getFileAttenteProspectMailRepositoryService', true],
        ], [
            'fileAttenteRepo' => 'App\\Repository\\FileAttenteProspectMailRepository',
        ]);
    }
}
