<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JHp3TbuService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.jHp3Tbu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jHp3Tbu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'whatsappRepo' => ['privates', 'App\\Repository\\FileAttenteWhatsappRepository', 'getFileAttenteWhatsappRepositoryService', true],
        ], [
            'userRepo' => 'App\\Repository\\UserRepository',
            'whatsappRepo' => 'App\\Repository\\FileAttenteWhatsappRepository',
        ]);
    }
}
