<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V2AkiIUService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.V2AkiIU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.V2AkiIU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'signalement' => ['privates', '.errored..service_locator.V2AkiIU.App\\Entity\\Signalement', NULL, 'Cannot autowire service ".service_locator.V2AkiIU": it references class "App\\Entity\\Signalement" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'signalement' => 'App\\Entity\\Signalement',
        ]);
    }
}
