<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YNwJxQvService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.yNwJxQv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yNwJxQv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'formulePromoAffaireRepository' => ['privates', 'App\\Repository\\FormulePromoAffaireRepository', 'getFormulePromoAffaireRepositoryService', true],
            'promotionRepository' => ['privates', 'App\\Repository\\PromotionRepository', 'getPromotionRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'verificationsDS' => ['services', 'App\\Services\\VerificationsDS', 'getVerificationsDSService', true],
        ], [
            'formulePromoAffaireRepository' => 'App\\Repository\\FormulePromoAffaireRepository',
            'promotionRepository' => 'App\\Repository\\PromotionRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
            'verificationsDS' => 'App\\Services\\VerificationsDS',
        ]);
    }
}
