<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Yyf8ajService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator._yyf8aj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._yyf8aj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'userBot' => ['privates', '.errored..service_locator._yyf8aj.App\\Entity\\UserBot', NULL, 'Cannot autowire service ".service_locator._yyf8aj": it references class "App\\Entity\\UserBot" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'userBot' => 'App\\Entity\\UserBot',
        ]);
    }
}
