<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_R062OwkService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.r062Owk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.r062Owk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'boostRepository' => ['privates', 'App\\Repository\\BoostRepository', 'getBoostRepositoryService', true],
            'cache' => ['services', 'cache.app', 'getCache_AppService', true],
            'cookieDS' => ['privates', 'App\\Services\\CookieDS', 'getCookieDSService', true],
            'deletedDSRepository' => ['privates', 'App\\Repository\\DeletedDSRepository', 'getDeletedDSRepositoryService', true],
            'promoReseauRepository' => ['privates', 'App\\Repository\\PromoReseauRepository', 'getPromoReseauRepositoryService', true],
            'promotionRepository' => ['privates', 'App\\Repository\\PromotionRepository', 'getPromotionRepositoryService', true],
            'traitementsDS' => ['services', 'App\\Services\\TraitementsDS', 'getTraitementsDSService', true],
            'transactionRepository' => ['privates', 'App\\Repository\\TransactionRepository', 'getTransactionRepositoryService', true],
            'userBotRepository' => ['privates', 'App\\Repository\\UserBotRepository', 'getUserBotRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'boostRepository' => 'App\\Repository\\BoostRepository',
            'cache' => '?',
            'cookieDS' => 'App\\Services\\CookieDS',
            'deletedDSRepository' => 'App\\Repository\\DeletedDSRepository',
            'promoReseauRepository' => 'App\\Repository\\PromoReseauRepository',
            'promotionRepository' => 'App\\Repository\\PromotionRepository',
            'traitementsDS' => 'App\\Services\\TraitementsDS',
            'transactionRepository' => 'App\\Repository\\TransactionRepository',
            'userBotRepository' => 'App\\Repository\\UserBotRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
