<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V0tJVHService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.v0tJ_vH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.v0tJ_vH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'methodePaiement' => ['privates', '.errored..service_locator.v0tJ_vH.App\\Entity\\MethodePaiement', NULL, 'Cannot autowire service ".service_locator.v0tJ_vH": it references class "App\\Entity\\MethodePaiement" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'methodePaiement' => 'App\\Entity\\MethodePaiement',
        ]);
    }
}
