<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QVNihEaService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.qVNihEa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qVNihEa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'motRefuser' => ['privates', '.errored..service_locator.qVNihEa.App\\Entity\\MotRefuser', NULL, 'Cannot autowire service ".service_locator.qVNihEa": it references class "App\\Entity\\MotRefuser" but no such service exists.'],
        ], [
            'motRefuser' => 'App\\Entity\\MotRefuser',
        ]);
    }
}
