<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__RMk629Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator..rMk629' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..rMk629'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'boostRepository' => ['privates', 'App\\Repository\\BoostRepository', 'getBoostRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'fileAttenteRepo' => ['privates', 'App\\Repository\\FileAttenteProspectMailRepository', 'getFileAttenteProspectMailRepositoryService', true],
            'promoReseauRepository' => ['privates', 'App\\Repository\\PromoReseauRepository', 'getPromoReseauRepositoryService', true],
            'promotionRepository' => ['privates', 'App\\Repository\\PromotionRepository', 'getPromotionRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'whatsappFileRepo' => ['privates', 'App\\Repository\\FileAttenteWhatsappRepository', 'getFileAttenteWhatsappRepositoryService', true],
        ], [
            'boostRepository' => 'App\\Repository\\BoostRepository',
            'entityManager' => '?',
            'fileAttenteRepo' => 'App\\Repository\\FileAttenteProspectMailRepository',
            'promoReseauRepository' => 'App\\Repository\\PromoReseauRepository',
            'promotionRepository' => 'App\\Repository\\PromotionRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
            'whatsappFileRepo' => 'App\\Repository\\FileAttenteWhatsappRepository',
        ]);
    }
}
