<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BgA4Cy7Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.bgA4Cy7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bgA4Cy7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'formulePromoReseauRepository' => ['privates', 'App\\Repository\\FormulePromoReseauRepository', 'getFormulePromoReseauRepositoryService', true],
        ], [
            'entityManager' => '?',
            'formulePromoReseauRepository' => 'App\\Repository\\FormulePromoReseauRepository',
        ]);
    }
}
