<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MV3S27PService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.MV3S27P' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MV3S27P'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'signalement' => ['privates', '.errored..service_locator.MV3S27P.App\\Entity\\Signalement', NULL, 'Cannot autowire service ".service_locator.MV3S27P": it references class "App\\Entity\\Signalement" but no such service exists.'],
        ], [
            'signalement' => 'App\\Entity\\Signalement',
        ]);
    }
}
