<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DdwmcahService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.ddwmcah' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ddwmcah'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'promotion' => ['privates', '.errored..service_locator.ddwmcah.App\\Entity\\Promotion', NULL, 'Cannot autowire service ".service_locator.ddwmcah": it references class "App\\Entity\\Promotion" but no such service exists.'],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'promotion' => 'App\\Entity\\Promotion',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
