<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JWlM9aJService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.JWlM9aJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JWlM9aJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cookieDS' => ['privates', 'App\\Services\\CookieDS', 'getCookieDSService', true],
            'formulePromoAffaireRepository' => ['privates', 'App\\Repository\\FormulePromoAffaireRepository', 'getFormulePromoAffaireRepositoryService', true],
            'promotionRepository' => ['privates', 'App\\Repository\\PromotionRepository', 'getPromotionRepositoryService', true],
            'sendMail' => ['privates', 'App\\Utilities\\SendMail', 'getSendMailService', true],
            'traitementsDS' => ['services', 'App\\Services\\TraitementsDS', 'getTraitementsDSService', true],
            'verificationsDS' => ['services', 'App\\Services\\VerificationsDS', 'getVerificationsDSService', true],
        ], [
            'cookieDS' => 'App\\Services\\CookieDS',
            'formulePromoAffaireRepository' => 'App\\Repository\\FormulePromoAffaireRepository',
            'promotionRepository' => 'App\\Repository\\PromotionRepository',
            'sendMail' => 'App\\Utilities\\SendMail',
            'traitementsDS' => 'App\\Services\\TraitementsDS',
            'verificationsDS' => 'App\\Services\\VerificationsDS',
        ]);
    }
}
