<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_W9ZpnQnService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.w9ZpnQn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.w9ZpnQn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'transactionRepository' => ['privates', 'App\\Repository\\TransactionRepository', 'getTransactionRepositoryService', true],
            'userBot' => ['privates', '.errored..service_locator.w9ZpnQn.App\\Entity\\UserBot', NULL, 'Cannot autowire service ".service_locator.w9ZpnQn": it references class "App\\Entity\\UserBot" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'transactionRepository' => 'App\\Repository\\TransactionRepository',
            'userBot' => 'App\\Entity\\UserBot',
        ]);
    }
}
