<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4iztvyFService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.4iztvyF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4iztvyF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'formuleBoostRepository' => ['privates', 'App\\Repository\\FormuleBoostRepository', 'getFormuleBoostRepositoryService', true],
            'traitementsDS' => ['services', 'App\\Services\\TraitementsDS', 'getTraitementsDSService', true],
        ], [
            'formuleBoostRepository' => 'App\\Repository\\FormuleBoostRepository',
            'traitementsDS' => 'App\\Services\\TraitementsDS',
        ]);
    }
}
