<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KK5hxPJService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.KK5hxPJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KK5hxPJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'storyRepository' => ['privates', 'App\\Repository\\StoryRepository', 'getStoryRepositoryService', true],
        ], [
            'storyRepository' => 'App\\Repository\\StoryRepository',
        ]);
    }
}
