<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3fjyV9WService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.3fjyV9W' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3fjyV9W'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'envMailSender' => ['privates', '.errored..service_locator.3fjyV9W.App\\Entity\\EnvMailSender', NULL, 'Cannot autowire service ".service_locator.3fjyV9W": it references class "App\\Entity\\EnvMailSender" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'envMailSender' => 'App\\Entity\\EnvMailSender',
        ]);
    }
}
