<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_W6SrBOyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.w6SrBOy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.w6SrBOy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'boostRepository' => ['privates', 'App\\Repository\\BoostRepository', 'getBoostRepositoryService', true],
            'cache' => ['services', 'cache.app', 'getCache_AppService', true],
            'fileAttenteRepo' => ['privates', 'App\\Repository\\FileAttenteProspectMailRepository', 'getFileAttenteProspectMailRepositoryService', true],
            'logRepo' => ['privates', 'App\\Repository\\LogBoiteMailRepository', 'getLogBoiteMailRepositoryService', true],
            'promoReseauRepository' => ['privates', 'App\\Repository\\PromoReseauRepository', 'getPromoReseauRepositoryService', true],
            'promotionRepository' => ['privates', 'App\\Repository\\PromotionRepository', 'getPromotionRepositoryService', true],
            'prospectRepo' => ['privates', 'App\\Repository\\MailProspectRepository', 'getMailProspectRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'whatsappRepo' => ['privates', 'App\\Repository\\FileAttenteWhatsappRepository', 'getFileAttenteWhatsappRepositoryService', true],
        ], [
            'boostRepository' => 'App\\Repository\\BoostRepository',
            'cache' => '?',
            'fileAttenteRepo' => 'App\\Repository\\FileAttenteProspectMailRepository',
            'logRepo' => 'App\\Repository\\LogBoiteMailRepository',
            'promoReseauRepository' => 'App\\Repository\\PromoReseauRepository',
            'promotionRepository' => 'App\\Repository\\PromotionRepository',
            'prospectRepo' => 'App\\Repository\\MailProspectRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
            'whatsappRepo' => 'App\\Repository\\FileAttenteWhatsappRepository',
        ]);
    }
}
