<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HEt487cService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.hEt487c' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hEt487c'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'tutoRepository' => ['privates', 'App\\Repository\\TutoRepository', 'getTutoRepositoryService', true],
            'verificationsDS' => ['services', 'App\\Services\\VerificationsDS', 'getVerificationsDSService', true],
        ], [
            'tutoRepository' => 'App\\Repository\\TutoRepository',
            'verificationsDS' => 'App\\Services\\VerificationsDS',
        ]);
    }
}
