<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RAXZ0TService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.RAXZ0T_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RAXZ0T_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'zefameApi' => ['privates', 'App\\Utilities\\ZefameApi', 'getZefameApiService', true],
        ], [
            'zefameApi' => 'App\\Utilities\\ZefameApi',
        ]);
    }
}
