<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_K_S3EyrService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.k.s3Eyr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.k.s3Eyr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'promotionRepository' => ['privates', 'App\\Repository\\PromotionRepository', 'getPromotionRepositoryService', true],
            'traitementsDS' => ['services', 'App\\Services\\TraitementsDS', 'getTraitementsDSService', true],
        ], [
            'promotionRepository' => 'App\\Repository\\PromotionRepository',
            'traitementsDS' => 'App\\Services\\TraitementsDS',
        ]);
    }
}
