<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DpA9PKService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.DpA9_PK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DpA9_PK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'boostRepository' => ['privates', 'App\\Repository\\BoostRepository', 'getBoostRepositoryService', true],
            'traitementsDS' => ['services', 'App\\Services\\TraitementsDS', 'getTraitementsDSService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'verificationsDS' => ['services', 'App\\Services\\VerificationsDS', 'getVerificationsDSService', true],
        ], [
            'boostRepository' => 'App\\Repository\\BoostRepository',
            'traitementsDS' => 'App\\Services\\TraitementsDS',
            'userRepository' => 'App\\Repository\\UserRepository',
            'verificationsDS' => 'App\\Services\\VerificationsDS',
        ]);
    }
}
