<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B2ECZODService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.B2ECZOD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.B2ECZOD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cache' => ['services', 'cache.app', 'getCache_AppService', true],
            'formulePromoReseauRepository' => ['privates', 'App\\Repository\\FormulePromoReseauRepository', 'getFormulePromoReseauRepositoryService', true],
        ], [
            'cache' => '?',
            'formulePromoReseauRepository' => 'App\\Repository\\FormulePromoReseauRepository',
        ]);
    }
}
