<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HRrAjEzService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.hRrAjEz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hRrAjEz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'envMailSenderRepository' => ['privates', 'App\\Repository\\EnvMailSenderRepository', 'getEnvMailSenderRepositoryService', true],
        ], [
            'envMailSenderRepository' => 'App\\Repository\\EnvMailSenderRepository',
        ]);
    }
}
