<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YxZ2bnbService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.YxZ2bnb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YxZ2bnb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'sendMail' => ['privates', 'App\\Utilities\\SendMail', 'getSendMailService', true],
            'userBotRepository' => ['privates', 'App\\Repository\\UserBotRepository', 'getUserBotRepositoryService', true],
            'verificationsDS' => ['services', 'App\\Services\\VerificationsDS', 'getVerificationsDSService', true],
        ], [
            'sendMail' => 'App\\Utilities\\SendMail',
            'userBotRepository' => 'App\\Repository\\UserBotRepository',
            'verificationsDS' => 'App\\Services\\VerificationsDS',
        ]);
    }
}
