<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZfEay1aService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.ZfEay1a' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZfEay1a'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'promoReseau' => ['privates', '.errored..service_locator.ZfEay1a.App\\Entity\\PromoReseau', NULL, 'Cannot autowire service ".service_locator.ZfEay1a": it references class "App\\Entity\\PromoReseau" but no such service exists.'],
        ], [
            'promoReseau' => 'App\\Entity\\PromoReseau',
        ]);
    }
}
