<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VE6HSTfService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.VE6HSTf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VE6HSTf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'deletedD' => ['privates', '.errored..service_locator.VE6HSTf.App\\Entity\\DeletedDS', NULL, 'Cannot autowire service ".service_locator.VE6HSTf": it references class "App\\Entity\\DeletedDS" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'deletedD' => 'App\\Entity\\DeletedDS',
            'entityManager' => '?',
        ]);
    }
}
