<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GloGMRgService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.gloGMRg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gloGMRg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'boost' => ['privates', '.errored..service_locator.gloGMRg.App\\Entity\\Boost', NULL, 'Cannot autowire service ".service_locator.gloGMRg": it references class "App\\Entity\\Boost" but no such service exists.'],
        ], [
            'boost' => 'App\\Entity\\Boost',
        ]);
    }
}
