<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C1WoGPLService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.C1WoGPL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.C1WoGPL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'boostRepository' => ['privates', 'App\\Repository\\BoostRepository', 'getBoostRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'promoReseauRepository' => ['privates', 'App\\Repository\\PromoReseauRepository', 'getPromoReseauRepositoryService', true],
            'promotionRepository' => ['privates', 'App\\Repository\\PromotionRepository', 'getPromotionRepositoryService', true],
        ], [
            'boostRepository' => 'App\\Repository\\BoostRepository',
            'entityManager' => '?',
            'promoReseauRepository' => 'App\\Repository\\PromoReseauRepository',
            'promotionRepository' => 'App\\Repository\\PromotionRepository',
        ]);
    }
}
