<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WTyF_OSService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.WTyF.OS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WTyF.OS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'envMailSender' => ['privates', '.errored..service_locator.WTyF.OS.App\\Entity\\EnvMailSender', NULL, 'Cannot autowire service ".service_locator.WTyF.OS": it references class "App\\Entity\\EnvMailSender" but no such service exists.'],
        ], [
            'envMailSender' => 'App\\Entity\\EnvMailSender',
        ]);
    }
}
