<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H6zyKl_Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.h6zyKl.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.h6zyKl.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'motRefuser' => ['privates', '.errored..service_locator.h6zyKl..App\\Entity\\MotRefuser', NULL, 'Cannot autowire service ".service_locator.h6zyKl.": it references class "App\\Entity\\MotRefuser" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'motRefuser' => 'App\\Entity\\MotRefuser',
        ]);
    }
}
