<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WnWozYOService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.wnWozYO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wnWozYO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'promotionRepository' => ['privates', 'App\\Repository\\PromotionRepository', 'getPromotionRepositoryService', true],
            'traitementsDS' => ['services', 'App\\Services\\TraitementsDS', 'getTraitementsDSService', true],
            'verificationsDS' => ['services', 'App\\Services\\VerificationsDS', 'getVerificationsDSService', true],
        ], [
            'promotionRepository' => 'App\\Repository\\PromotionRepository',
            'traitementsDS' => 'App\\Services\\TraitementsDS',
            'verificationsDS' => 'App\\Services\\VerificationsDS',
        ]);
    }
}
