<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XwFaLLBService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.XwFaLLB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XwFaLLB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'promoReseau' => ['privates', '.errored..service_locator.XwFaLLB.App\\Entity\\PromoReseau', NULL, 'Cannot autowire service ".service_locator.XwFaLLB": it references class "App\\Entity\\PromoReseau" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'promoReseau' => 'App\\Entity\\PromoReseau',
        ]);
    }
}
