<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TtvVyinService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.ttvVyin' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ttvVyin'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cache' => ['services', 'cache.app', 'getCache_AppService', true],
            'formuleBoostRepository' => ['privates', 'App\\Repository\\FormuleBoostRepository', 'getFormuleBoostRepositoryService', true],
            'formuleDressurBotRepository' => ['privates', 'App\\Repository\\FormuleDressurBotRepository', 'getFormuleDressurBotRepositoryService', true],
            'formulePromoAffaireRepository' => ['privates', 'App\\Repository\\FormulePromoAffaireRepository', 'getFormulePromoAffaireRepositoryService', true],
            'formulePromoReseauRepository' => ['privates', 'App\\Repository\\FormulePromoReseauRepository', 'getFormulePromoReseauRepositoryService', true],
        ], [
            'cache' => '?',
            'formuleBoostRepository' => 'App\\Repository\\FormuleBoostRepository',
            'formuleDressurBotRepository' => 'App\\Repository\\FormuleDressurBotRepository',
            'formulePromoAffaireRepository' => 'App\\Repository\\FormulePromoAffaireRepository',
            'formulePromoReseauRepository' => 'App\\Repository\\FormulePromoReseauRepository',
        ]);
    }
}
