<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8o1XFnpService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.8o1XFnp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8o1XFnp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'traitementsDS' => ['services', 'App\\Services\\TraitementsDS', 'getTraitementsDSService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'verifMailRepository' => ['privates', 'App\\Repository\\VerifMailRepository', 'getVerifMailRepositoryService', true],
            'verificationsDS' => ['services', 'App\\Services\\VerificationsDS', 'getVerificationsDSService', true],
        ], [
            'traitementsDS' => 'App\\Services\\TraitementsDS',
            'userRepository' => 'App\\Repository\\UserRepository',
            'verifMailRepository' => 'App\\Repository\\VerifMailRepository',
            'verificationsDS' => 'App\\Services\\VerificationsDS',
        ]);
    }
}
