<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBoost2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.gloGMRg.App\Entity\Boost' shared service.
     *
     * @return \App\Entity\Boost
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.gloGMRg": it references class "App\\Entity\\Boost" but no such service exists.');
    }
}
