<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\API\ContactController' shared autowired service.
     *
     * @return \App\Controller\API\ContactController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\API\\ContactController'] = $instance = new \App\Controller\API\ContactController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['App\\Services\\CookieDS'] ?? $container->load('getCookieDSService')), ($container->privates['App\\Utilities\\SendMail'] ?? $container->load('getSendMailService')));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\API\\ContactController', $container));

        return $instance;
    }
}
