<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCookieDSService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Services\CookieDS' shared autowired service.
     *
     * @return \App\Services\CookieDS
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Services\\CookieDS'] = new \App\Services\CookieDS(($container->privates['parameter_bag'] ?? ($container->privates['parameter_bag'] = new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container))));
    }
}
