<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCrudEnvMailSenderControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Crud\CrudEnvMailSenderController' shared autowired service.
     *
     * @return \App\Controller\Crud\CrudEnvMailSenderController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Crud\\CrudEnvMailSenderController'] = $instance = new \App\Controller\Crud\CrudEnvMailSenderController(($container->privates['App\\Services\\CookieDS'] ?? $container->load('getCookieDSService')), ($container->services['App\\Services\\TraitementsDS'] ?? $container->load('getTraitementsDSService')));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\Crud\\CrudEnvMailSenderController', $container));

        return $instance;
    }
}
