<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCrudUserControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Crud\CrudUserController' shared autowired service.
     *
     * @return \App\Controller\Crud\CrudUserController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Crud\\CrudUserController'] = $instance = new \App\Controller\Crud\CrudUserController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Services\\CookieDS'] ?? $container->load('getCookieDSService')), ($container->services['App\\Services\\TraitementsDS'] ?? $container->load('getTraitementsDSService')), ($container->privates['App\\Repository\\EnvRepository'] ?? $container->load('getEnvRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\Crud\\CrudUserController', $container));

        return $instance;
    }
}
