<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConfirmMailControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ConfirmMailController' shared autowired service.
     *
     * @return \App\Controller\ConfirmMailController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ConfirmMailController'] = $instance = new \App\Controller\ConfirmMailController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\ConfirmMailController', $container));

        return $instance;
    }
}
