<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCrudDeletedDSControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Crud\CrudDeletedDSController' shared autowired service.
     *
     * @return \App\Controller\Crud\CrudDeletedDSController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Crud\\CrudDeletedDSController'] = $instance = new \App\Controller\Crud\CrudDeletedDSController(($container->privates['App\\Services\\CookieDS'] ?? $container->load('getCookieDSService')), ($container->services['App\\Services\\TraitementsDS'] ?? $container->load('getTraitementsDSService')));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\Crud\\CrudDeletedDSController', $container));

        return $instance;
    }
}
