<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_Orm_DefaultEntityManagerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'doctrine.orm.default_entity_manager' shared service.
     *
     * @return \Doctrine\ORM\EntityManager
     */
    public static function do($container, $lazyLoad = true)
    {
        if ($lazyLoad) {
            return $container->services['doctrine.orm.default_entity_manager'] = $container->createProxy('EntityManager_9a5be93', function () use ($container) {
                return \EntityManager_9a5be93::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) use ($container) {
                    $wrappedInstance = self::do($container, false);

                    $proxy->setProxyInitializer(null);

                    return true;
                });
            });
        }

        $a = new \Doctrine\ORM\Configuration();

        $b = new \Doctrine\Persistence\Mapping\Driver\MappingDriverChain();
        $b->addDriver(new \Doctrine\ORM\Mapping\Driver\AttributeDriver([0 => (\dirname(__DIR__, 4).'/src/Entity')], false), 'App\\Entity');

        $a->setEntityNamespaces(['App' => 'App\\Entity']);
        $a->setMetadataCache(new \Symfony\Component\Cache\Adapter\PhpArrayAdapter(($container->targetDir.''.'/doctrine/orm/default_metadata.php'), new \Symfony\Component\Cache\Adapter\ArrayAdapter()));
        $a->setQueryCache(($container->privates['doctrine.system_cache_pool'] ?? $container->load('getDoctrine_SystemCachePoolService')));
        $a->setResultCache(($container->privates['doctrine.result_cache_pool'] ?? $container->load('getDoctrine_ResultCachePoolService')));
        $a->setMetadataDriverImpl(new \Doctrine\Bundle\DoctrineBundle\Mapping\MappingDriver($b, new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine.ulid_generator' => ['privates', 'doctrine.ulid_generator', 'getDoctrine_UlidGeneratorService', true],
            'doctrine.uuid_generator' => ['privates', 'doctrine.uuid_generator', 'getDoctrine_UuidGeneratorService', true],
        ], [
            'doctrine.ulid_generator' => '?',
            'doctrine.uuid_generator' => '?',
        ])));
        $a->setProxyDir(($container->targetDir.''.'/doctrine/orm/Proxies'));
        $a->setProxyNamespace('Proxies');
        $a->setAutoGenerateProxyClasses(false);
        $a->setSchemaIgnoreClasses([]);
        $a->setClassMetadataFactoryName('Doctrine\\Bundle\\DoctrineBundle\\Mapping\\ClassMetadataFactory');
        $a->setDefaultRepositoryClassName('Doctrine\\ORM\\EntityRepository');
        $a->setNamingStrategy(new \Doctrine\ORM\Mapping\UnderscoreNamingStrategy(0, true));
        $a->setQuoteStrategy(new \Doctrine\ORM\Mapping\DefaultQuoteStrategy());
        $a->setTypedFieldMapper(new \Doctrine\ORM\Mapping\DefaultTypedFieldMapper());
        $a->setEntityListenerResolver(new \Doctrine\Bundle\DoctrineBundle\Mapping\ContainerEntityListenerResolver($container));
        $a->setLazyGhostObjectEnabled(false);
        $a->setIdentityGenerationPreferences([]);
        $a->setRepositoryFactory(new \Doctrine\Bundle\DoctrineBundle\Repository\ContainerRepositoryFactory(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Repository\\AffiliationUsedRepository' => ['privates', 'App\\Repository\\AffiliationUsedRepository', 'getAffiliationUsedRepositoryService', true],
            'App\\Repository\\BoostRepository' => ['privates', 'App\\Repository\\BoostRepository', 'getBoostRepositoryService', true],
            'App\\Repository\\ChatMessageRepository' => ['privates', 'App\\Repository\\ChatMessageRepository', 'getChatMessageRepositoryService', true],
            'App\\Repository\\ContactRepository' => ['privates', 'App\\Repository\\ContactRepository', 'getContactRepositoryService', true],
            'App\\Repository\\DeletedDSRepository' => ['privates', 'App\\Repository\\DeletedDSRepository', 'getDeletedDSRepositoryService', true],
            'App\\Repository\\EnvMailSenderRepository' => ['privates', 'App\\Repository\\EnvMailSenderRepository', 'getEnvMailSenderRepositoryService', true],
            'App\\Repository\\EnvPaiementApiRepository' => ['privates', 'App\\Repository\\EnvPaiementApiRepository', 'getEnvPaiementApiRepositoryService', true],
            'App\\Repository\\EnvRepository' => ['privates', 'App\\Repository\\EnvRepository', 'getEnvRepositoryService', true],
            'App\\Repository\\FileAttenteProspectMailRepository' => ['privates', 'App\\Repository\\FileAttenteProspectMailRepository', 'getFileAttenteProspectMailRepositoryService', true],
            'App\\Repository\\FileAttenteWhatsappRepository' => ['privates', 'App\\Repository\\FileAttenteWhatsappRepository', 'getFileAttenteWhatsappRepositoryService', true],
            'App\\Repository\\FormuleBoostRepository' => ['privates', 'App\\Repository\\FormuleBoostRepository', 'getFormuleBoostRepositoryService', true],
            'App\\Repository\\FormuleDressurBotRepository' => ['privates', 'App\\Repository\\FormuleDressurBotRepository', 'getFormuleDressurBotRepositoryService', true],
            'App\\Repository\\FormulePromoAffaireRepository' => ['privates', 'App\\Repository\\FormulePromoAffaireRepository', 'getFormulePromoAffaireRepositoryService', true],
            'App\\Repository\\FormulePromoReseauRepository' => ['privates', 'App\\Repository\\FormulePromoReseauRepository', 'getFormulePromoReseauRepositoryService', true],
            'App\\Repository\\HistoriqueProgrammeRecompenseRepository' => ['privates', 'App\\Repository\\HistoriqueProgrammeRecompenseRepository', 'getHistoriqueProgrammeRecompenseRepositoryService', true],
            'App\\Repository\\LogBoiteMailRepository' => ['privates', 'App\\Repository\\LogBoiteMailRepository', 'getLogBoiteMailRepositoryService', true],
            'App\\Repository\\MailProspectRepository' => ['privates', 'App\\Repository\\MailProspectRepository', 'getMailProspectRepositoryService', true],
            'App\\Repository\\MessageRepository' => ['privates', 'App\\Repository\\MessageRepository', 'getMessageRepositoryService', true],
            'App\\Repository\\MethodePaiementRepository' => ['privates', 'App\\Repository\\MethodePaiementRepository', 'getMethodePaiementRepositoryService', true],
            'App\\Repository\\MotRefuserRepository' => ['privates', 'App\\Repository\\MotRefuserRepository', 'getMotRefuserRepositoryService', true],
            'App\\Repository\\NotificationRepository' => ['privates', 'App\\Repository\\NotificationRepository', 'getNotificationRepositoryService', true],
            'App\\Repository\\PreferenceRepository' => ['privates', 'App\\Repository\\PreferenceRepository', 'getPreferenceRepositoryService', true],
            'App\\Repository\\PreuveRepository' => ['privates', 'App\\Repository\\PreuveRepository', 'getPreuveRepositoryService', true],
            'App\\Repository\\PromoReseauRepository' => ['privates', 'App\\Repository\\PromoReseauRepository', 'getPromoReseauRepositoryService', true],
            'App\\Repository\\PromotionRepository' => ['privates', 'App\\Repository\\PromotionRepository', 'getPromotionRepositoryService', true],
            'App\\Repository\\SignalementRepository' => ['privates', 'App\\Repository\\SignalementRepository', 'getSignalementRepositoryService', true],
            'App\\Repository\\StoryRepository' => ['privates', 'App\\Repository\\StoryRepository', 'getStoryRepositoryService', true],
            'App\\Repository\\SuggestionRepository' => ['privates', 'App\\Repository\\SuggestionRepository', 'getSuggestionRepositoryService', true],
            'App\\Repository\\TransactionRepository' => ['privates', 'App\\Repository\\TransactionRepository', 'getTransactionRepositoryService', true],
            'App\\Repository\\TutoRepository' => ['privates', 'App\\Repository\\TutoRepository', 'getTutoRepositoryService', true],
            'App\\Repository\\UserBotRepository' => ['privates', 'App\\Repository\\UserBotRepository', 'getUserBotRepositoryService', true],
            'App\\Repository\\UserRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'App\\Repository\\VerifMailRepository' => ['privates', 'App\\Repository\\VerifMailRepository', 'getVerifMailRepositoryService', true],
        ], [
            'App\\Repository\\AffiliationUsedRepository' => '?',
            'App\\Repository\\BoostRepository' => '?',
            'App\\Repository\\ChatMessageRepository' => '?',
            'App\\Repository\\ContactRepository' => '?',
            'App\\Repository\\DeletedDSRepository' => '?',
            'App\\Repository\\EnvMailSenderRepository' => '?',
            'App\\Repository\\EnvPaiementApiRepository' => '?',
            'App\\Repository\\EnvRepository' => '?',
            'App\\Repository\\FileAttenteProspectMailRepository' => '?',
            'App\\Repository\\FileAttenteWhatsappRepository' => '?',
            'App\\Repository\\FormuleBoostRepository' => '?',
            'App\\Repository\\FormuleDressurBotRepository' => '?',
            'App\\Repository\\FormulePromoAffaireRepository' => '?',
            'App\\Repository\\FormulePromoReseauRepository' => '?',
            'App\\Repository\\HistoriqueProgrammeRecompenseRepository' => '?',
            'App\\Repository\\LogBoiteMailRepository' => '?',
            'App\\Repository\\MailProspectRepository' => '?',
            'App\\Repository\\MessageRepository' => '?',
            'App\\Repository\\MethodePaiementRepository' => '?',
            'App\\Repository\\MotRefuserRepository' => '?',
            'App\\Repository\\NotificationRepository' => '?',
            'App\\Repository\\PreferenceRepository' => '?',
            'App\\Repository\\PreuveRepository' => '?',
            'App\\Repository\\PromoReseauRepository' => '?',
            'App\\Repository\\PromotionRepository' => '?',
            'App\\Repository\\SignalementRepository' => '?',
            'App\\Repository\\StoryRepository' => '?',
            'App\\Repository\\SuggestionRepository' => '?',
            'App\\Repository\\TransactionRepository' => '?',
            'App\\Repository\\TutoRepository' => '?',
            'App\\Repository\\UserBotRepository' => '?',
            'App\\Repository\\UserRepository' => '?',
            'App\\Repository\\VerifMailRepository' => '?',
        ])));

        $instance = new \Doctrine\ORM\EntityManager(($container->services['doctrine.dbal.default_connection'] ?? $container->load('getDoctrine_Dbal_DefaultConnectionService')), $a, ($container->privates['doctrine.dbal.default_connection.event_manager'] ?? $container->load('getDoctrine_Dbal_DefaultConnection_EventManagerService')));

        (new \Doctrine\Bundle\DoctrineBundle\ManagerConfigurator([], []))->configure($instance);

        return $instance;
    }
}
