<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeletedDS2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.VE6HSTf.App\Entity\DeletedDS' shared service.
     *
     * @return \App\Entity\DeletedDS
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.VE6HSTf": it references class "App\\Entity\\DeletedDS" but no such service exists.');
    }
}
