<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEspacePartenaireControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\API\EspacePartenaireController' shared autowired service.
     *
     * @return \App\Controller\API\EspacePartenaireController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\API\\EspacePartenaireController'] = $instance = new \App\Controller\API\EspacePartenaireController(($container->services['App\\Services\\TraitementsDS'] ?? $container->load('getTraitementsDSService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['App\\Repository\\AffiliationUsedRepository'] ?? $container->load('getAffiliationUsedRepositoryService')), ($container->privates['App\\Services\\CookieDS'] ?? $container->load('getCookieDSService')));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\API\\EspacePartenaireController', $container));

        return $instance;
    }
}
