<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnvMailSender2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.WTyF.OS.App\Entity\EnvMailSender' shared service.
     *
     * @return \App\Entity\EnvMailSender
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.WTyF.OS": it references class "App\\Entity\\EnvMailSender" but no such service exists.');
    }
}
