<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnvPaiementApi2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.xFfi3eF.App\Entity\EnvPaiementApi' shared service.
     *
     * @return \App\Entity\EnvPaiementApi
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.xFfi3eF": it references class "App\\Entity\\EnvPaiementApi" but no such service exists.');
    }
}
