<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnvMailSenderRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\EnvMailSenderRepository' shared autowired service.
     *
     * @return \App\Repository\EnvMailSenderRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\EnvMailSenderRepository'] = new \App\Repository\EnvMailSenderRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
