<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormuleDressurBotTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\FormuleDressurBotType' shared autowired service.
     *
     * @return \App\Form\FormuleDressurBotType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\FormuleDressurBotType'] = new \App\Form\FormuleDressurBotType();
    }
}
