<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormuleDressurBotService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.GFkPXpW.App\Entity\FormuleDressurBot' shared service.
     *
     * @return \App\Entity\FormuleDressurBot
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.GFkPXpW": it references class "App\\Entity\\FormuleDressurBot" but no such service exists.');
    }
}
