<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormuleBoost2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.iMLmNej.App\Entity\FormuleBoost' shared service.
     *
     * @return \App\Entity\FormuleBoost
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.iMLmNej": it references class "App\\Entity\\FormuleBoost" but no such service exists.');
    }
}
