<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFileAttenteProspectMailService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.TbeidcY.App\Entity\FileAttenteProspectMail' shared service.
     *
     * @return \App\Entity\FileAttenteProspectMail
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.TbeidcY": it references class "App\\Entity\\FileAttenteProspectMail" but no such service exists.');
    }
}
