<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormulePromoAffaire2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.T8TFfbT.App\Entity\FormulePromoAffaire' shared service.
     *
     * @return \App\Entity\FormulePromoAffaire
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.T8TFfbT": it references class "App\\Entity\\FormulePromoAffaire" but no such service exists.');
    }
}
