<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormulePromoReseauService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.Cyurbgx.App\Entity\FormulePromoReseau' shared service.
     *
     * @return \App\Entity\FormulePromoReseau
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Cyurbgx": it references class "App\\Entity\\FormulePromoReseau" but no such service exists.');
    }
}
