<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForm_RegistryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'form.registry' shared service.
     *
     * @return \Symfony\Component\Form\FormRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['form.registry'] = new \Symfony\Component\Form\FormRegistry([0 => new \Symfony\Component\Form\Extension\DependencyInjection\DependencyInjectionExtension(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Form\\BoostType' => ['privates', 'App\\Form\\BoostType', 'getBoostTypeService', true],
            'App\\Form\\DeletedDSType' => ['privates', 'App\\Form\\DeletedDSType', 'getDeletedDSTypeService', true],
            'App\\Form\\EnvMailSenderType' => ['privates', 'App\\Form\\EnvMailSenderType', 'getEnvMailSenderTypeService', true],
            'App\\Form\\EnvPaiementApiType' => ['privates', 'App\\Form\\EnvPaiementApiType', 'getEnvPaiementApiTypeService', true],
            'App\\Form\\EnvType' => ['privates', 'App\\Form\\EnvType', 'getEnvTypeService', true],
            'App\\Form\\FormuleBoostType' => ['privates', 'App\\Form\\FormuleBoostType', 'getFormuleBoostTypeService', true],
            'App\\Form\\FormuleDressurBotType' => ['privates', 'App\\Form\\FormuleDressurBotType', 'getFormuleDressurBotTypeService', true],
            'App\\Form\\FormulePromoAffaireType' => ['privates', 'App\\Form\\FormulePromoAffaireType', 'getFormulePromoAffaireTypeService', true],
            'App\\Form\\FormulePromoReseauType' => ['privates', 'App\\Form\\FormulePromoReseauType', 'getFormulePromoReseauTypeService', true],
            'App\\Form\\HistoriqueProgrammeRecompenseType' => ['privates', 'App\\Form\\HistoriqueProgrammeRecompenseType', 'getHistoriqueProgrammeRecompenseTypeService', true],
            'App\\Form\\MethodePaiementType' => ['privates', 'App\\Form\\MethodePaiementType', 'getMethodePaiementTypeService', true],
            'App\\Form\\MotRefuserType' => ['privates', 'App\\Form\\MotRefuserType', 'getMotRefuserTypeService', true],
            'App\\Form\\PreuveType' => ['privates', 'App\\Form\\PreuveType', 'getPreuveTypeService', true],
            'App\\Form\\PromoReseauType' => ['privates', 'App\\Form\\PromoReseauType', 'getPromoReseauTypeService', true],
            'App\\Form\\PromotionType' => ['privates', 'App\\Form\\PromotionType', 'getPromotionTypeService', true],
            'App\\Form\\SignalementType' => ['privates', 'App\\Form\\SignalementType', 'getSignalementTypeService', true],
            'App\\Form\\SuggestionType' => ['privates', 'App\\Form\\SuggestionType', 'getSuggestionTypeService', true],
            'App\\Form\\TransactionType' => ['privates', 'App\\Form\\TransactionType', 'getTransactionTypeService', true],
            'App\\Form\\TutoType' => ['privates', 'App\\Form\\TutoType', 'getTutoTypeService', true],
            'App\\Form\\UserBotType' => ['privates', 'App\\Form\\UserBotType', 'getUserBotTypeService', true],
            'App\\Form\\UserType' => ['privates', 'App\\Form\\UserType', 'getUserTypeService', true],
            'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => ['privates', 'form.type.entity', 'getForm_Type_EntityService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => ['privates', 'form.type.choice', 'getForm_Type_ChoiceService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ColorType' => ['privates', 'form.type.color', 'getForm_Type_ColorService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FileType' => ['privates', 'form.type.file', 'getForm_Type_FileService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => ['privates', 'form.type.form', 'getForm_Type_FormService', true],
        ], [
            'App\\Form\\BoostType' => '?',
            'App\\Form\\DeletedDSType' => '?',
            'App\\Form\\EnvMailSenderType' => '?',
            'App\\Form\\EnvPaiementApiType' => '?',
            'App\\Form\\EnvType' => '?',
            'App\\Form\\FormuleBoostType' => '?',
            'App\\Form\\FormuleDressurBotType' => '?',
            'App\\Form\\FormulePromoAffaireType' => '?',
            'App\\Form\\FormulePromoReseauType' => '?',
            'App\\Form\\HistoriqueProgrammeRecompenseType' => '?',
            'App\\Form\\MethodePaiementType' => '?',
            'App\\Form\\MotRefuserType' => '?',
            'App\\Form\\PreuveType' => '?',
            'App\\Form\\PromoReseauType' => '?',
            'App\\Form\\PromotionType' => '?',
            'App\\Form\\SignalementType' => '?',
            'App\\Form\\SuggestionType' => '?',
            'App\\Form\\TransactionType' => '?',
            'App\\Form\\TutoType' => '?',
            'App\\Form\\UserBotType' => '?',
            'App\\Form\\UserType' => '?',
            'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ColorType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FileType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => '?',
        ]), ['Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.form.transformation_failure_handling'] ?? $container->load('getForm_TypeExtension_Form_TransformationFailureHandlingService'));
            yield 1 => ($container->privates['form.type_extension.form.http_foundation'] ?? $container->load('getForm_TypeExtension_Form_HttpFoundationService'));
            yield 2 => ($container->privates['form.type_extension.form.validator'] ?? $container->load('getForm_TypeExtension_Form_ValidatorService'));
            yield 3 => ($container->privates['form.type_extension.upload.validator'] ?? $container->load('getForm_TypeExtension_Upload_ValidatorService'));
            yield 4 => ($container->privates['form.type_extension.csrf'] ?? $container->load('getForm_TypeExtension_CsrfService'));
        }, 5), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\RepeatedType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.repeated.validator'] ?? ($container->privates['form.type_extension.repeated.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\RepeatedTypeValidatorExtension()));
        }, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\SubmitType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.submit.validator'] ?? ($container->privates['form.type_extension.submit.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\SubmitTypeValidatorExtension()));
        }, 1)], new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_guesser.validator'] ?? $container->load('getForm_TypeGuesser_ValidatorService'));
            yield 1 => ($container->privates['form.type_guesser.doctrine'] ?? $container->load('getForm_TypeGuesser_DoctrineService'));
        }, 2))], new \Symfony\Component\Form\ResolvedFormTypeFactory());
    }
}
