<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHistoriqueProgrammeRecompense2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.Wx0zikl.App\Entity\HistoriqueProgrammeRecompense' shared service.
     *
     * @return \App\Entity\HistoriqueProgrammeRecompense
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Wx0zikl": it references class "App\\Entity\\HistoriqueProgrammeRecompense" but no such service exists.');
    }
}
