<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMethodePaiementService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.Z3G._xo.App\Entity\MethodePaiement' shared service.
     *
     * @return \App\Entity\MethodePaiement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Z3G._xo": it references class "App\\Entity\\MethodePaiement" but no such service exists.');
    }
}
