<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMotRefuserService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.h6zyKl..App\Entity\MotRefuser' shared service.
     *
     * @return \App\Entity\MotRefuser
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.h6zyKl.": it references class "App\\Entity\\MotRefuser" but no such service exists.');
    }
}
