<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromoReseau3Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.ZfEay1a.App\Entity\PromoReseau' shared service.
     *
     * @return \App\Entity\PromoReseau
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ZfEay1a": it references class "App\\Entity\\PromoReseau" but no such service exists.');
    }
}
