<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPreuve4Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.fhMIAfe.App\Entity\Preuve' shared service.
     *
     * @return \App\Entity\Preuve
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.fhMIAfe": it references class "App\\Entity\\Preuve" but no such service exists.');
    }
}
