<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrivateControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\PrivateController' shared autowired service.
     *
     * @return \App\Controller\PrivateController
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'));

        if (isset($container->services['App\\Controller\\PrivateController'])) {
            return $container->services['App\\Controller\\PrivateController'];
        }
        $b = ($container->services['App\\Services\\TraitementsDS'] ?? $container->load('getTraitementsDSService'));

        if (isset($container->services['App\\Controller\\PrivateController'])) {
            return $container->services['App\\Controller\\PrivateController'];
        }

        $container->services['App\\Controller\\PrivateController'] = $instance = new \App\Controller\PrivateController($a, ($container->privates['App\\Repository\\EnvRepository'] ?? $container->load('getEnvRepositoryService')), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['App\\Services\\CookieDS'] ?? $container->load('getCookieDSService')), $b, ($container->privates['App\\Repository\\FormulePromoReseauRepository'] ?? $container->load('getFormulePromoReseauRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\PrivateController', $container));

        return $instance;
    }
}
