<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPreuveRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\PreuveRepository' shared autowired service.
     *
     * @return \App\Repository\PreuveRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\PreuveRepository'] = new \App\Repository\PreuveRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
