<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPurgeControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\API\PurgeController' shared autowired service.
     *
     * @return \App\Controller\API\PurgeController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\API\\PurgeController'] = $instance = new \App\Controller\API\PurgeController(($container->services['App\\Services\\TraitementsDS'] ?? $container->load('getTraitementsDSService')));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\API\\PurgeController', $container));

        return $instance;
    }
}
