<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendMailService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Utilities\SendMail' shared autowired service.
     *
     * @return \App\Utilities\SendMail
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'));

        if (isset($container->privates['App\\Utilities\\SendMail'])) {
            return $container->privates['App\\Utilities\\SendMail'];
        }

        return $container->privates['App\\Utilities\\SendMail'] = new \App\Utilities\SendMail(($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()), $a, ($container->privates['App\\Repository\\EnvMailSenderRepository'] ?? $container->load('getEnvMailSenderRepositoryService')));
    }
}
