<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStory2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.JeDCUF5.App\Entity\Story' shared service.
     *
     * @return \App\Entity\Story
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.JeDCUF5": it references class "App\\Entity\\Story" but no such service exists.');
    }
}
