<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuggestion2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.jknI0A1.App\Entity\Suggestion' shared service.
     *
     * @return \App\Entity\Suggestion
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.jknI0A1": it references class "App\\Entity\\Suggestion" but no such service exists.');
    }
}
