<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuggestionTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\SuggestionType' shared autowired service.
     *
     * @return \App\Form\SuggestionType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\SuggestionType'] = new \App\Form\SuggestionType();
    }
}
