<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSignalementControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\API\SignalementController' shared autowired service.
     *
     * @return \App\Controller\API\SignalementController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\API\\SignalementController'] = $instance = new \App\Controller\API\SignalementController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\EnvRepository'] ?? $container->load('getEnvRepositoryService')), ($container->services['App\\Controller\\API\\UserController'] ?? $container->load('getUserControllerService')), ($container->privates['App\\Services\\CookieDS'] ?? $container->load('getCookieDSService')));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\API\\SignalementController', $container));

        return $instance;
    }
}
