<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSignalement2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.V2AkiIU.App\Entity\Signalement' shared service.
     *
     * @return \App\Entity\Signalement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.V2AkiIU": it references class "App\\Entity\\Signalement" but no such service exists.');
    }
}
