<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStoryControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\API\StoryController' shared autowired service.
     *
     * @return \App\Controller\API\StoryController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\API\\StoryController'] = $instance = new \App\Controller\API\StoryController(($container->privates['App\\Utilities\\SendMail'] ?? $container->load('getSendMailService')));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\API\\StoryController', $container));

        return $instance;
    }
}
