<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSessionDSService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Services\SessionDS' shared autowired service.
     *
     * @return \App\Services\SessionDS
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Services\\SessionDS'] = new \App\Services\SessionDS();
    }
}
