<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransactionService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.3PHq.pi.App\Entity\Transaction' shared service.
     *
     * @return \App\Entity\Transaction
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.3PHq.pi": it references class "App\\Entity\\Transaction" but no such service exists.');
    }
}
