<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTutoService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.Mu24nTq.App\Entity\Tuto' shared service.
     *
     * @return \App\Entity\Tuto
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Mu24nTq": it references class "App\\Entity\\Tuto" but no such service exists.');
    }
}
