<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserBot3Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.w9ZpnQn.App\Entity\UserBot' shared service.
     *
     * @return \App\Entity\UserBot
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.w9ZpnQn": it references class "App\\Entity\\UserBot" but no such service exists.');
    }
}
