<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserPreferenceControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\API\UserPreferenceController' shared autowired service.
     *
     * @return \App\Controller\API\UserPreferenceController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\API\\UserPreferenceController'] = $instance = new \App\Controller\API\UserPreferenceController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\API\\UserPreferenceController', $container));

        return $instance;
    }
}
