<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVerificationsDSService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Services\VerificationsDS' shared autowired service.
     *
     * @return \App\Services\VerificationsDS
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Services\\VerificationsDS'] = $instance = new \App\Services\VerificationsDS(($container->privates['App\\Repository\\MotRefuserRepository'] ?? $container->load('getMotRefuserRepositoryService')), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['App\\Services\\SessionDS'] ?? ($container->privates['App\\Services\\SessionDS'] = new \App\Services\SessionDS())));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Services\\VerificationsDS', $container));

        return $instance;
    }
}
