<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWebhookControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\API\WebhookController' shared autowired service.
     *
     * @return \App\Controller\API\WebhookController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\API\\WebhookController'] = $instance = new \App\Controller\API\WebhookController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\TransactionRepository'] ?? $container->load('getTransactionRepositoryService')), ($container->privates['App\\Repository\\FormuleBoostRepository'] ?? $container->load('getFormuleBoostRepositoryService')), ($container->privates['App\\Repository\\PromotionRepository'] ?? $container->load('getPromotionRepositoryService')), ($container->privates['App\\Repository\\FormulePromoReseauRepository'] ?? $container->load('getFormulePromoReseauRepositoryService')), ($container->services['App\\Services\\VerificationsDS'] ?? $container->load('getVerificationsDSService')), ($container->privates['App\\Repository\\BoostRepository'] ?? $container->load('getBoostRepositoryService')), ($container->privates['App\\Repository\\FormuleDressurBotRepository'] ?? $container->load('getFormuleDressurBotRepositoryService')), ($container->privates['App\\Repository\\FormulePromoAffaireRepository'] ?? $container->load('getFormulePromoAffaireRepositoryService')), ($container->privates['App\\Utilities\\SendMail'] ?? $container->load('getSendMailService')), ($container->privates['App\\Utilities\\ZefameApi'] ?? ($container->privates['App\\Utilities\\ZefameApi'] = new \App\Utilities\ZefameApi())), ($container->services['App\\Services\\TraitementsDS'] ?? $container->load('getTraitementsDSService')));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\API\\WebhookController', $container));

        return $instance;
    }
}
