<?php

namespace ContainerXXAK4c3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getZefameApiService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Utilities\ZefameApi' shared autowired service.
     *
     * @return \App\Utilities\ZefameApi
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Utilities\\ZefameApi'] = new \App\Utilities\ZefameApi();
    }
}
