<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Env extends \App\Entity\Env implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Env' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Env' . "\0" . 'versionApp', '' . "\0" . 'App\\Entity\\Env' . "\0" . 'importantUpdate', '' . "\0" . 'App\\Entity\\Env' . "\0" . 'usersTel', '' . "\0" . 'App\\Entity\\Env' . "\0" . 'versionDressurBot', '' . "\0" . 'App\\Entity\\Env' . "\0" . 'userBanned', '' . "\0" . 'App\\Entity\\Env' . "\0" . 'iaActive'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Env' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Env' . "\0" . 'versionApp', '' . "\0" . 'App\\Entity\\Env' . "\0" . 'importantUpdate', '' . "\0" . 'App\\Entity\\Env' . "\0" . 'usersTel', '' . "\0" . 'App\\Entity\\Env' . "\0" . 'versionDressurBot', '' . "\0" . 'App\\Entity\\Env' . "\0" . 'userBanned', '' . "\0" . 'App\\Entity\\Env' . "\0" . 'iaActive'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Env $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function addUsersTel($tel_or_mail): \App\Entity\Env
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUsersTel', [$tel_or_mail]);

        return parent::addUsersTel($tel_or_mail);
    }

    /**
     * {@inheritDoc}
     */
    public function addUserBanned($tel_or_mail): \App\Entity\Env
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUserBanned', [$tel_or_mail]);

        return parent::addUserBanned($tel_or_mail);
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getVersionApp(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVersionApp', []);

        return parent::getVersionApp();
    }

    /**
     * {@inheritDoc}
     */
    public function setVersionApp(string $versionApp): \App\Entity\Env
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVersionApp', [$versionApp]);

        return parent::setVersionApp($versionApp);
    }

    /**
     * {@inheritDoc}
     */
    public function getImportantUpdate(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImportantUpdate', []);

        return parent::getImportantUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setImportantUpdate(?bool $importantUpdate): \App\Entity\Env
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImportantUpdate', [$importantUpdate]);

        return parent::setImportantUpdate($importantUpdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsersTel(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsersTel', []);

        return parent::getUsersTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsersTel(?array $usersTel): \App\Entity\Env
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsersTel', [$usersTel]);

        return parent::setUsersTel($usersTel);
    }

    /**
     * {@inheritDoc}
     */
    public function getVersionDressurBot(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVersionDressurBot', []);

        return parent::getVersionDressurBot();
    }

    /**
     * {@inheritDoc}
     */
    public function setVersionDressurBot(?string $versionDressurBot): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVersionDressurBot', [$versionDressurBot]);

        return parent::setVersionDressurBot($versionDressurBot);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserBanned(): ?array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserBanned', []);

        return parent::getUserBanned();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserBanned(?array $userBanned): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserBanned', [$userBanned]);

        return parent::setUserBanned($userBanned);
    }

    /**
     * {@inheritDoc}
     */
    public function isIaActive(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isIaActive', []);

        return parent::isIaActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setIaActive(bool $iaActive): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIaActive', [$iaActive]);

        return parent::setIaActive($iaActive);
    }

}
