<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Boost extends \App\Entity\Boost implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Boost' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Boost' . "\0" . 'formuleBoost', '' . "\0" . 'App\\Entity\\Boost' . "\0" . 'dateDebut', '' . "\0" . 'App\\Entity\\Boost' . "\0" . 'dateExp', '' . "\0" . 'App\\Entity\\Boost' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Boost' . "\0" . 'mode', '' . "\0" . 'App\\Entity\\Boost' . "\0" . 'source', '' . "\0" . 'App\\Entity\\Boost' . "\0" . 'typeBoost', '' . "\0" . 'App\\Entity\\Boost' . "\0" . 'nbContactsObtenus'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Boost' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Boost' . "\0" . 'formuleBoost', '' . "\0" . 'App\\Entity\\Boost' . "\0" . 'dateDebut', '' . "\0" . 'App\\Entity\\Boost' . "\0" . 'dateExp', '' . "\0" . 'App\\Entity\\Boost' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Boost' . "\0" . 'mode', '' . "\0" . 'App\\Entity\\Boost' . "\0" . 'source', '' . "\0" . 'App\\Entity\\Boost' . "\0" . 'typeBoost', '' . "\0" . 'App\\Entity\\Boost' . "\0" . 'nbContactsObtenus'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Boost $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getFormuleBoost(): ?\App\Entity\FormuleBoost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormuleBoost', []);

        return parent::getFormuleBoost();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormuleBoost(?\App\Entity\FormuleBoost $formuleBoost): \App\Entity\Boost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormuleBoost', [$formuleBoost]);

        return parent::setFormuleBoost($formuleBoost);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDebut(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDebut', []);

        return parent::getDateDebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDebut(\DateTimeInterface $dateDebut): \App\Entity\Boost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDebut', [$dateDebut]);

        return parent::setDateDebut($dateDebut);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateExp(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateExp', []);

        return parent::getDateExp();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateExp(?\DateTimeInterface $dateExp): \App\Entity\Boost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateExp', [$dateExp]);

        return parent::setDateExp($dateExp);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(?\App\Entity\User $user): \App\Entity\Boost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getMode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMode', []);

        return parent::getMode();
    }

    /**
     * {@inheritDoc}
     */
    public function setMode(string $mode): \App\Entity\Boost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMode', [$mode]);

        return parent::setMode($mode);
    }

    /**
     * {@inheritDoc}
     */
    public function getSource(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSource', []);

        return parent::getSource();
    }

    /**
     * {@inheritDoc}
     */
    public function setSource(?string $source): \App\Entity\Boost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSource', [$source]);

        return parent::setSource($source);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeBoost(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeBoost', []);

        return parent::getTypeBoost();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeBoost(string $typeBoost): \App\Entity\Boost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeBoost', [$typeBoost]);

        return parent::setTypeBoost($typeBoost);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbContactsObtenus(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbContactsObtenus', []);

        return parent::getNbContactsObtenus();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbContactsObtenus(?int $nbContactsObtenus): \App\Entity\Boost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbContactsObtenus', [$nbContactsObtenus]);

        return parent::setNbContactsObtenus($nbContactsObtenus);
    }

}
