<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PromoReseau extends \App\Entity\PromoReseau implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\PromoReseau' . "\0" . 'id', '' . "\0" . 'App\\Entity\\PromoReseau' . "\0" . 'user', '' . "\0" . 'App\\Entity\\PromoReseau' . "\0" . 'formulePromoReseau', '' . "\0" . 'App\\Entity\\PromoReseau' . "\0" . 'qteDemander', '' . "\0" . 'App\\Entity\\PromoReseau' . "\0" . 'prixFixer', '' . "\0" . 'App\\Entity\\PromoReseau' . "\0" . 'url', '' . "\0" . 'App\\Entity\\PromoReseau' . "\0" . 'status', '' . "\0" . 'App\\Entity\\PromoReseau' . "\0" . 'idZefame', '' . "\0" . 'App\\Entity\\PromoReseau' . "\0" . 'compteurDebut', '' . "\0" . 'App\\Entity\\PromoReseau' . "\0" . 'compteurRestant', '' . "\0" . 'App\\Entity\\PromoReseau' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\PromoReseau' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\PromoReseau' . "\0" . 'prixZefame', '' . "\0" . 'App\\Entity\\PromoReseau' . "\0" . 'source'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\PromoReseau' . "\0" . 'id', '' . "\0" . 'App\\Entity\\PromoReseau' . "\0" . 'user', '' . "\0" . 'App\\Entity\\PromoReseau' . "\0" . 'formulePromoReseau', '' . "\0" . 'App\\Entity\\PromoReseau' . "\0" . 'qteDemander', '' . "\0" . 'App\\Entity\\PromoReseau' . "\0" . 'prixFixer', '' . "\0" . 'App\\Entity\\PromoReseau' . "\0" . 'url', '' . "\0" . 'App\\Entity\\PromoReseau' . "\0" . 'status', '' . "\0" . 'App\\Entity\\PromoReseau' . "\0" . 'idZefame', '' . "\0" . 'App\\Entity\\PromoReseau' . "\0" . 'compteurDebut', '' . "\0" . 'App\\Entity\\PromoReseau' . "\0" . 'compteurRestant', '' . "\0" . 'App\\Entity\\PromoReseau' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\PromoReseau' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\PromoReseau' . "\0" . 'prixZefame', '' . "\0" . 'App\\Entity\\PromoReseau' . "\0" . 'source'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PromoReseau $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(?\App\Entity\User $user): \App\Entity\PromoReseau
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormulePromoReseau(): ?\App\Entity\FormulePromoReseau
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormulePromoReseau', []);

        return parent::getFormulePromoReseau();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormulePromoReseau(?\App\Entity\FormulePromoReseau $formulePromoReseau): \App\Entity\PromoReseau
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormulePromoReseau', [$formulePromoReseau]);

        return parent::setFormulePromoReseau($formulePromoReseau);
    }

    /**
     * {@inheritDoc}
     */
    public function getQteDemander(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQteDemander', []);

        return parent::getQteDemander();
    }

    /**
     * {@inheritDoc}
     */
    public function setQteDemander(int $qteDemander): \App\Entity\PromoReseau
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQteDemander', [$qteDemander]);

        return parent::setQteDemander($qteDemander);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixFixer(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixFixer', []);

        return parent::getPrixFixer();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixFixer(int $prixFixer): \App\Entity\PromoReseau
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixFixer', [$prixFixer]);

        return parent::setPrixFixer($prixFixer);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrl(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrl', []);

        return parent::getUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrl(string $url): \App\Entity\PromoReseau
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrl', [$url]);

        return parent::setUrl($url);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(int $status): \App\Entity\PromoReseau
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdZefame(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdZefame', []);

        return parent::getIdZefame();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdZefame(?string $idZefame): \App\Entity\PromoReseau
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdZefame', [$idZefame]);

        return parent::setIdZefame($idZefame);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompteurDebut(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompteurDebut', []);

        return parent::getCompteurDebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompteurDebut(?int $compteurDebut): \App\Entity\PromoReseau
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompteurDebut', [$compteurDebut]);

        return parent::setCompteurDebut($compteurDebut);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompteurRestant(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompteurRestant', []);

        return parent::getCompteurRestant();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompteurRestant(?int $compteurRestant): \App\Entity\PromoReseau
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompteurRestant', [$compteurRestant]);

        return parent::setCompteurRestant($compteurRestant);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTimeInterface $createdAt): \App\Entity\PromoReseau
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTimeInterface $updatedAt): \App\Entity\PromoReseau
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixZefame(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixZefame', []);

        return parent::getPrixZefame();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixZefame(?float $prixZefame): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixZefame', [$prixZefame]);

        return parent::setPrixZefame($prixZefame);
    }

    /**
     * {@inheritDoc}
     */
    public function getSource(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSource', []);

        return parent::getSource();
    }

    /**
     * {@inheritDoc}
     */
    public function setSource(?string $source): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSource', [$source]);

        return parent::setSource($source);
    }

}
