<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Transaction extends \App\Entity\Transaction implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'idTransaction', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'reference', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'amount', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'customerId', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'currencyId', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'annotherInfo', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'transactionFor', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'userBot'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'idTransaction', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'reference', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'amount', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'customerId', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'currencyId', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'annotherInfo', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'transactionFor', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'userBot'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Transaction $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdTransaction(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTransaction', []);

        return parent::getIdTransaction();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdTransaction(?string $idTransaction): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdTransaction', [$idTransaction]);

        return parent::setIdTransaction($idTransaction);
    }

    /**
     * {@inheritDoc}
     */
    public function getReference(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReference', []);

        return parent::getReference();
    }

    /**
     * {@inheritDoc}
     */
    public function setReference(string $reference): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReference', [$reference]);

        return parent::setReference($reference);
    }

    /**
     * {@inheritDoc}
     */
    public function getAmount(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAmount', []);

        return parent::getAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setAmount(?int $amount): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAmount', [$amount]);

        return parent::setAmount($amount);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(?string $status): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerId(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerId', []);

        return parent::getCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerId(?int $customerId): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerId', [$customerId]);

        return parent::setCustomerId($customerId);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrencyId(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrencyId', []);

        return parent::getCurrencyId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrencyId(?int $currencyId): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrencyId', [$currencyId]);

        return parent::setCurrencyId($currencyId);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(?\DateTimeInterface $createdAt): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(?\DateTimeInterface $updatedAt): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function isUpdated(): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isUpdated', []);

        return parent::isUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(?\App\Entity\User $user): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnotherInfo(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnotherInfo', []);

        return parent::getAnnotherInfo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnnotherInfo(?array $annotherInfo): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnnotherInfo', [$annotherInfo]);

        return parent::setAnnotherInfo($annotherInfo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTransactionFor(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransactionFor', []);

        return parent::getTransactionFor();
    }

    /**
     * {@inheritDoc}
     */
    public function setTransactionFor(?string $transactionFor): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTransactionFor', [$transactionFor]);

        return parent::setTransactionFor($transactionFor);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserBot(): ?\App\Entity\UserBot
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserBot', []);

        return parent::getUserBot();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserBot(?\App\Entity\UserBot $userBot): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserBot', [$userBot]);

        return parent::setUserBot($userBot);
    }

}
