<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MethodePaiement extends \App\Entity\MethodePaiement implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\MethodePaiement' . "\0" . 'id', '' . "\0" . 'App\\Entity\\MethodePaiement' . "\0" . 'aggregator', '' . "\0" . 'App\\Entity\\MethodePaiement' . "\0" . 'pays', '' . "\0" . 'App\\Entity\\MethodePaiement' . "\0" . 'titre', '' . "\0" . 'App\\Entity\\MethodePaiement' . "\0" . 'code', '' . "\0" . 'App\\Entity\\MethodePaiement' . "\0" . 'activated', '' . "\0" . 'App\\Entity\\MethodePaiement' . "\0" . 'isdirect', '' . "\0" . 'App\\Entity\\MethodePaiement' . "\0" . 'requires', '' . "\0" . 'App\\Entity\\MethodePaiement' . "\0" . 'typeFeexPay', '' . "\0" . 'App\\Entity\\MethodePaiement' . "\0" . 'codePays'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\MethodePaiement' . "\0" . 'id', '' . "\0" . 'App\\Entity\\MethodePaiement' . "\0" . 'aggregator', '' . "\0" . 'App\\Entity\\MethodePaiement' . "\0" . 'pays', '' . "\0" . 'App\\Entity\\MethodePaiement' . "\0" . 'titre', '' . "\0" . 'App\\Entity\\MethodePaiement' . "\0" . 'code', '' . "\0" . 'App\\Entity\\MethodePaiement' . "\0" . 'activated', '' . "\0" . 'App\\Entity\\MethodePaiement' . "\0" . 'isdirect', '' . "\0" . 'App\\Entity\\MethodePaiement' . "\0" . 'requires', '' . "\0" . 'App\\Entity\\MethodePaiement' . "\0" . 'typeFeexPay', '' . "\0" . 'App\\Entity\\MethodePaiement' . "\0" . 'codePays'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MethodePaiement $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getAggregator(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAggregator', []);

        return parent::getAggregator();
    }

    /**
     * {@inheritDoc}
     */
    public function setAggregator(string $aggregator): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAggregator', [$aggregator]);

        return parent::setAggregator($aggregator);
    }

    /**
     * {@inheritDoc}
     */
    public function getPays(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPays', []);

        return parent::getPays();
    }

    /**
     * {@inheritDoc}
     */
    public function setPays(string $pays): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPays', [$pays]);

        return parent::setPays($pays);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', []);

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre(string $titre): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', [$titre]);

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode(string $code): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function isActivated(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isActivated', []);

        return parent::isActivated();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivated(bool $activated): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivated', [$activated]);

        return parent::setActivated($activated);
    }

    /**
     * {@inheritDoc}
     */
    public function isIsdirect(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isIsdirect', []);

        return parent::isIsdirect();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsdirect(bool $isdirect): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsdirect', [$isdirect]);

        return parent::setIsdirect($isdirect);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequires(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequires', []);

        return parent::getRequires();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequires(?string $requires): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequires', [$requires]);

        return parent::setRequires($requires);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeFeexPay(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeFeexPay', []);

        return parent::getTypeFeexPay();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeFeexPay(?string $typeFeexPay): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeFeexPay', [$typeFeexPay]);

        return parent::setTypeFeexPay($typeFeexPay);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodePays(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodePays', []);

        return parent::getCodePays();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodePays(?string $codePays): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodePays', [$codePays]);

        return parent::setCodePays($codePays);
    }

}
