<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EnvMailSender extends \App\Entity\EnvMailSender implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\EnvMailSender' . "\0" . 'id', '' . "\0" . 'App\\Entity\\EnvMailSender' . "\0" . 'mailAdresse', '' . "\0" . 'App\\Entity\\EnvMailSender' . "\0" . 'password', '' . "\0" . 'App\\Entity\\EnvMailSender' . "\0" . 'smtpServer', '' . "\0" . 'App\\Entity\\EnvMailSender' . "\0" . 'smtpPort', '' . "\0" . 'App\\Entity\\EnvMailSender' . "\0" . 'smtpSecured', '' . "\0" . 'App\\Entity\\EnvMailSender' . "\0" . 'activated', '' . "\0" . 'App\\Entity\\EnvMailSender' . "\0" . 'countMailSent', '' . "\0" . 'App\\Entity\\EnvMailSender' . "\0" . 'lastUsedAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\EnvMailSender' . "\0" . 'id', '' . "\0" . 'App\\Entity\\EnvMailSender' . "\0" . 'mailAdresse', '' . "\0" . 'App\\Entity\\EnvMailSender' . "\0" . 'password', '' . "\0" . 'App\\Entity\\EnvMailSender' . "\0" . 'smtpServer', '' . "\0" . 'App\\Entity\\EnvMailSender' . "\0" . 'smtpPort', '' . "\0" . 'App\\Entity\\EnvMailSender' . "\0" . 'smtpSecured', '' . "\0" . 'App\\Entity\\EnvMailSender' . "\0" . 'activated', '' . "\0" . 'App\\Entity\\EnvMailSender' . "\0" . 'countMailSent', '' . "\0" . 'App\\Entity\\EnvMailSender' . "\0" . 'lastUsedAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EnvMailSender $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getMailAdresse(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailAdresse', []);

        return parent::getMailAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setMailAdresse(string $mailAdresse): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMailAdresse', [$mailAdresse]);

        return parent::setMailAdresse($mailAdresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword(string $password): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getSmtpServer(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSmtpServer', []);

        return parent::getSmtpServer();
    }

    /**
     * {@inheritDoc}
     */
    public function setSmtpServer(string $smtpServer): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSmtpServer', [$smtpServer]);

        return parent::setSmtpServer($smtpServer);
    }

    /**
     * {@inheritDoc}
     */
    public function getSmtpPort(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSmtpPort', []);

        return parent::getSmtpPort();
    }

    /**
     * {@inheritDoc}
     */
    public function setSmtpPort(string $smtpPort): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSmtpPort', [$smtpPort]);

        return parent::setSmtpPort($smtpPort);
    }

    /**
     * {@inheritDoc}
     */
    public function getSmtpSecured(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSmtpSecured', []);

        return parent::getSmtpSecured();
    }

    /**
     * {@inheritDoc}
     */
    public function setSmtpSecured(string $smtpSecured): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSmtpSecured', [$smtpSecured]);

        return parent::setSmtpSecured($smtpSecured);
    }

    /**
     * {@inheritDoc}
     */
    public function isActivated(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isActivated', []);

        return parent::isActivated();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivated(bool $activated): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivated', [$activated]);

        return parent::setActivated($activated);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountMailSent(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountMailSent', []);

        return parent::getCountMailSent();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountMailSent(int $countMailSent): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountMailSent', [$countMailSent]);

        return parent::setCountMailSent($countMailSent);
    }

    /**
     * {@inheritDoc}
     */
    public function isUsed(): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isUsed', []);

        return parent::isUsed();
    }

    /**
     * {@inheritDoc}
     */
    public function getLastUsedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastUsedAt', []);

        return parent::getLastUsedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastUsedAt(?\DateTimeInterface $lastUsedAt): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastUsedAt', [$lastUsedAt]);

        return parent::setLastUsedAt($lastUsedAt);
    }

}
