<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FormulePromoReseau extends \App\Entity\FormulePromoReseau implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\FormulePromoReseau' . "\0" . 'id', '' . "\0" . 'App\\Entity\\FormulePromoReseau' . "\0" . 'parent', '' . "\0" . 'App\\Entity\\FormulePromoReseau' . "\0" . 'titre', '' . "\0" . 'App\\Entity\\FormulePromoReseau' . "\0" . 'description', '' . "\0" . 'App\\Entity\\FormulePromoReseau' . "\0" . 'prix', '' . "\0" . 'App\\Entity\\FormulePromoReseau' . "\0" . 'qte', '' . "\0" . 'App\\Entity\\FormulePromoReseau' . "\0" . 'qteMin', '' . "\0" . 'App\\Entity\\FormulePromoReseau' . "\0" . 'qteMax', '' . "\0" . 'App\\Entity\\FormulePromoReseau' . "\0" . 'sonFormulePromoReseaus', '' . "\0" . 'App\\Entity\\FormulePromoReseau' . "\0" . 'available', '' . "\0" . 'App\\Entity\\FormulePromoReseau' . "\0" . 'idZefame', '' . "\0" . 'App\\Entity\\FormulePromoReseau' . "\0" . 'prixZefame', '' . "\0" . 'App\\Entity\\FormulePromoReseau' . "\0" . 'prixVendeur'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\FormulePromoReseau' . "\0" . 'id', '' . "\0" . 'App\\Entity\\FormulePromoReseau' . "\0" . 'parent', '' . "\0" . 'App\\Entity\\FormulePromoReseau' . "\0" . 'titre', '' . "\0" . 'App\\Entity\\FormulePromoReseau' . "\0" . 'description', '' . "\0" . 'App\\Entity\\FormulePromoReseau' . "\0" . 'prix', '' . "\0" . 'App\\Entity\\FormulePromoReseau' . "\0" . 'qte', '' . "\0" . 'App\\Entity\\FormulePromoReseau' . "\0" . 'qteMin', '' . "\0" . 'App\\Entity\\FormulePromoReseau' . "\0" . 'qteMax', '' . "\0" . 'App\\Entity\\FormulePromoReseau' . "\0" . 'sonFormulePromoReseaus', '' . "\0" . 'App\\Entity\\FormulePromoReseau' . "\0" . 'available', '' . "\0" . 'App\\Entity\\FormulePromoReseau' . "\0" . 'idZefame', '' . "\0" . 'App\\Entity\\FormulePromoReseau' . "\0" . 'prixZefame', '' . "\0" . 'App\\Entity\\FormulePromoReseau' . "\0" . 'prixVendeur'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FormulePromoReseau $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', []);

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre(string $titre): \App\Entity\FormulePromoReseau
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', [$titre]);

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(?string $description): \App\Entity\FormulePromoReseau
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getQteMin(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQteMin', []);

        return parent::getQteMin();
    }

    /**
     * {@inheritDoc}
     */
    public function setQteMin(?int $qteMin): \App\Entity\FormulePromoReseau
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQteMin', [$qteMin]);

        return parent::setQteMin($qteMin);
    }

    /**
     * {@inheritDoc}
     */
    public function getQteMax(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQteMax', []);

        return parent::getQteMax();
    }

    /**
     * {@inheritDoc}
     */
    public function setQteMax(?int $qteMax): \App\Entity\FormulePromoReseau
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQteMax', [$qteMax]);

        return parent::setQteMax($qteMax);
    }

    /**
     * {@inheritDoc}
     */
    public function isAvailable(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAvailable', []);

        return parent::isAvailable();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvailable(bool $available): \App\Entity\FormulePromoReseau
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvailable', [$available]);

        return parent::setAvailable($available);
    }

    /**
     * {@inheritDoc}
     */
    public function getParent(): ?\App\Entity\FormulePromoReseau
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParent', []);

        return parent::getParent();
    }

    /**
     * {@inheritDoc}
     */
    public function setParent(?\App\Entity\FormulePromoReseau $parent): \App\Entity\FormulePromoReseau
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParent', [$parent]);

        return parent::setParent($parent);
    }

    /**
     * {@inheritDoc}
     */
    public function getSonFormulePromoReseaus(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSonFormulePromoReseaus', []);

        return parent::getSonFormulePromoReseaus();
    }

    /**
     * {@inheritDoc}
     */
    public function addSonFormulePromoReseau(\App\Entity\FormulePromoReseau $sonFormulePromoReseau): \App\Entity\FormulePromoReseau
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSonFormulePromoReseau', [$sonFormulePromoReseau]);

        return parent::addSonFormulePromoReseau($sonFormulePromoReseau);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSonFormulePromoReseau(\App\Entity\FormulePromoReseau $sonFormulePromoReseau): \App\Entity\FormulePromoReseau
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSonFormulePromoReseau', [$sonFormulePromoReseau]);

        return parent::removeSonFormulePromoReseau($sonFormulePromoReseau);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', []);

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix(?float $prix): \App\Entity\FormulePromoReseau
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', [$prix]);

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getQte(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQte', []);

        return parent::getQte();
    }

    /**
     * {@inheritDoc}
     */
    public function setQte(?int $qte): \App\Entity\FormulePromoReseau
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQte', [$qte]);

        return parent::setQte($qte);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdZefame(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdZefame', []);

        return parent::getIdZefame();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdZefame(?int $idZefame): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdZefame', [$idZefame]);

        return parent::setIdZefame($idZefame);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixZefame(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixZefame', []);

        return parent::getPrixZefame();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixZefame(?float $prixZefame): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixZefame', [$prixZefame]);

        return parent::setPrixZefame($prixZefame);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixVendeur(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixVendeur', []);

        return parent::getPrixVendeur();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixVendeur(?float $prixVendeur): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixVendeur', [$prixVendeur]);

        return parent::setPrixVendeur($prixVendeur);
    }

}
