<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Promotion extends \App\Entity\Promotion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'formulePromoAffaire', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'image', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'dateDebut', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'dateExp', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'nombreDeVue', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'mode', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'nombreImpression', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'limited', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'whoSaw', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'motif', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'isFakeVue', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'referencement', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'annotherInfo', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'typePromotionAffaire', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'inProgrammeRecompense', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'publishOnDressurStatus', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'source', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'boostFacebook', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'montantBoostFacebook', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'whatsappContact', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'nomSiteApp', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'urlSiteApp', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'sousTypeSiteApp', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'motifsRefus'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'formulePromoAffaire', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'image', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'dateDebut', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'dateExp', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'nombreDeVue', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'mode', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'nombreImpression', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'limited', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'whoSaw', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'motif', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'isFakeVue', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'referencement', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'annotherInfo', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'typePromotionAffaire', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'inProgrammeRecompense', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'publishOnDressurStatus', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'source', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'boostFacebook', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'montantBoostFacebook', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'whatsappContact', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'nomSiteApp', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'urlSiteApp', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'sousTypeSiteApp', '' . "\0" . 'App\\Entity\\Promotion' . "\0" . 'motifsRefus'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Promotion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getFormulePromoAffaire(): ?\App\Entity\FormulePromoAffaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormulePromoAffaire', []);

        return parent::getFormulePromoAffaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormulePromoAffaire(?\App\Entity\FormulePromoAffaire $formulePromoAffaire): \App\Entity\Promotion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormulePromoAffaire', [$formulePromoAffaire]);

        return parent::setFormulePromoAffaire($formulePromoAffaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(?\App\Entity\User $user): \App\Entity\Promotion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Entity\Promotion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage(string $image): \App\Entity\Promotion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDebut(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDebut', []);

        return parent::getDateDebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDebut(?\DateTimeInterface $dateDebut): \App\Entity\Promotion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDebut', [$dateDebut]);

        return parent::setDateDebut($dateDebut);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateExp(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateExp', []);

        return parent::getDateExp();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateExp(?\DateTimeInterface $dateExp): \App\Entity\Promotion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateExp', [$dateExp]);

        return parent::setDateExp($dateExp);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(int $status): \App\Entity\Promotion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreDeVue(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreDeVue', []);

        return parent::getNombreDeVue();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreDeVue(int $nombreDeVue): \App\Entity\Promotion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreDeVue', [$nombreDeVue]);

        return parent::setNombreDeVue($nombreDeVue);
    }

    /**
     * {@inheritDoc}
     */
    public function getMode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMode', []);

        return parent::getMode();
    }

    /**
     * {@inheritDoc}
     */
    public function setToWatch($user, $mode): \App\Entity\Promotion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setToWatch', [$user, $mode]);

        return parent::setToWatch($user, $mode);
    }

    /**
     * {@inheritDoc}
     */
    public function setMode(string $mode): \App\Entity\Promotion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMode', [$mode]);

        return parent::setMode($mode);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreImpression(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreImpression', []);

        return parent::getNombreImpression();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreImpression(?int $nombreImpression): \App\Entity\Promotion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreImpression', [$nombreImpression]);

        return parent::setNombreImpression($nombreImpression);
    }

    /**
     * {@inheritDoc}
     */
    public function isLimited(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isLimited', []);

        return parent::isLimited();
    }

    /**
     * {@inheritDoc}
     */
    public function setLimited(bool $limited): \App\Entity\Promotion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLimited', [$limited]);

        return parent::setLimited($limited);
    }

    /**
     * {@inheritDoc}
     */
    public function getWhoSaw(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWhoSaw', []);

        return parent::getWhoSaw();
    }

    /**
     * {@inheritDoc}
     */
    public function setWhoSaw(?array $whoSaw): \App\Entity\Promotion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWhoSaw', [$whoSaw]);

        return parent::setWhoSaw($whoSaw);
    }

    /**
     * {@inheritDoc}
     */
    public function getMotif(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotif', []);

        return parent::getMotif();
    }

    /**
     * {@inheritDoc}
     */
    public function setMotif(?string $motif): \App\Entity\Promotion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotif', [$motif]);

        return parent::setMotif($motif);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsFakeVue(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsFakeVue', []);

        return parent::getIsFakeVue();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsFakeVue(?bool $isFakeVue): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsFakeVue', [$isFakeVue]);

        return parent::setIsFakeVue($isFakeVue);
    }

    /**
     * {@inheritDoc}
     */
    public function getReferencement(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferencement', []);

        return parent::getReferencement();
    }

    /**
     * {@inheritDoc}
     */
    public function setReferencement(bool $referencement): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReferencement', [$referencement]);

        return parent::setReferencement($referencement);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnotherInfo(): ?array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnotherInfo', []);

        return parent::getAnnotherInfo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnnotherInfo(?array $annotherInfo): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnnotherInfo', [$annotherInfo]);

        return parent::setAnnotherInfo($annotherInfo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypePromotionAffaire(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypePromotionAffaire', []);

        return parent::getTypePromotionAffaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypePromotionAffaire(?string $typePromotionAffaire): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypePromotionAffaire', [$typePromotionAffaire]);

        return parent::setTypePromotionAffaire($typePromotionAffaire);
    }

    /**
     * {@inheritDoc}
     */
    public function isInProgrammeRecompense(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isInProgrammeRecompense', []);

        return parent::isInProgrammeRecompense();
    }

    /**
     * {@inheritDoc}
     */
    public function setInProgrammeRecompense(bool $inProgrammeRecompense): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInProgrammeRecompense', [$inProgrammeRecompense]);

        return parent::setInProgrammeRecompense($inProgrammeRecompense);
    }

    /**
     * {@inheritDoc}
     */
    public function isPublishOnDressurStatus(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPublishOnDressurStatus', []);

        return parent::isPublishOnDressurStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublishOnDressurStatus(bool $publishOnDressurStatus): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublishOnDressurStatus', [$publishOnDressurStatus]);

        return parent::setPublishOnDressurStatus($publishOnDressurStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getSource(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSource', []);

        return parent::getSource();
    }

    /**
     * {@inheritDoc}
     */
    public function setSource(?string $source): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSource', [$source]);

        return parent::setSource($source);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(?\DateTimeInterface $createdAt): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function isBoostFacebook(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isBoostFacebook', []);

        return parent::isBoostFacebook();
    }

    /**
     * {@inheritDoc}
     */
    public function setBoostFacebook(bool $boostFacebook): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBoostFacebook', [$boostFacebook]);

        return parent::setBoostFacebook($boostFacebook);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontantBoostFacebook(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontantBoostFacebook', []);

        return parent::getMontantBoostFacebook();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontantBoostFacebook(?int $montantBoostFacebook): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontantBoostFacebook', [$montantBoostFacebook]);

        return parent::setMontantBoostFacebook($montantBoostFacebook);
    }

    /**
     * {@inheritDoc}
     */
    public function getWhatsappContact(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWhatsappContact', []);

        return parent::getWhatsappContact();
    }

    /**
     * {@inheritDoc}
     */
    public function setWhatsappContact(?string $whatsappContact): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWhatsappContact', [$whatsappContact]);

        return parent::setWhatsappContact($whatsappContact);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomSiteApp(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomSiteApp', []);

        return parent::getNomSiteApp();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomSiteApp(?string $nomSiteApp): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomSiteApp', [$nomSiteApp]);

        return parent::setNomSiteApp($nomSiteApp);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrlSiteApp(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrlSiteApp', []);

        return parent::getUrlSiteApp();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrlSiteApp(?string $urlSiteApp): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrlSiteApp', [$urlSiteApp]);

        return parent::setUrlSiteApp($urlSiteApp);
    }

    /**
     * {@inheritDoc}
     */
    public function getSousTypeSiteApp(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSousTypeSiteApp', []);

        return parent::getSousTypeSiteApp();
    }

    /**
     * {@inheritDoc}
     */
    public function setSousTypeSiteApp(?string $sousTypeSiteApp): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSousTypeSiteApp', [$sousTypeSiteApp]);

        return parent::setSousTypeSiteApp($sousTypeSiteApp);
    }

    /**
     * {@inheritDoc}
     */
    public function getMotifsRefus(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotifsRefus', []);

        return parent::getMotifsRefus();
    }

    /**
     * {@inheritDoc}
     */
    public function addMotifRefus(\App\Entity\PromotionMotifRefus $motifRefus): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMotifRefus', [$motifRefus]);

        return parent::addMotifRefus($motifRefus);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMotifRefus(\App\Entity\PromotionMotifRefus $motifRefus): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMotifRefus', [$motifRefus]);

        return parent::removeMotifRefus($motifRefus);
    }

}
