<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FormuleBoost extends \App\Entity\FormuleBoost implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\FormuleBoost' . "\0" . 'id', '' . "\0" . 'App\\Entity\\FormuleBoost' . "\0" . 'titre', '' . "\0" . 'App\\Entity\\FormuleBoost' . "\0" . 'prix', '' . "\0" . 'App\\Entity\\FormuleBoost' . "\0" . 'nbrJour', '' . "\0" . 'App\\Entity\\FormuleBoost' . "\0" . 'alert', '' . "\0" . 'App\\Entity\\FormuleBoost' . "\0" . 'activated', '' . "\0" . 'App\\Entity\\FormuleBoost' . "\0" . 'typeBoost', '' . "\0" . 'App\\Entity\\FormuleBoost' . "\0" . 'nbContactsMax'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\FormuleBoost' . "\0" . 'id', '' . "\0" . 'App\\Entity\\FormuleBoost' . "\0" . 'titre', '' . "\0" . 'App\\Entity\\FormuleBoost' . "\0" . 'prix', '' . "\0" . 'App\\Entity\\FormuleBoost' . "\0" . 'nbrJour', '' . "\0" . 'App\\Entity\\FormuleBoost' . "\0" . 'alert', '' . "\0" . 'App\\Entity\\FormuleBoost' . "\0" . 'activated', '' . "\0" . 'App\\Entity\\FormuleBoost' . "\0" . 'typeBoost', '' . "\0" . 'App\\Entity\\FormuleBoost' . "\0" . 'nbContactsMax'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FormuleBoost $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', []);

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre(string $titre): \App\Entity\FormuleBoost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', [$titre]);

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', []);

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix(float $prix): \App\Entity\FormuleBoost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', [$prix]);

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbrJour(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbrJour', []);

        return parent::getNbrJour();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbrJour(int $nbrJour): \App\Entity\FormuleBoost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbrJour', [$nbrJour]);

        return parent::setNbrJour($nbrJour);
    }

    /**
     * {@inheritDoc}
     */
    public function isAlert(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAlert', []);

        return parent::isAlert();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlert(bool $alert): \App\Entity\FormuleBoost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlert', [$alert]);

        return parent::setAlert($alert);
    }

    /**
     * {@inheritDoc}
     */
    public function isActivated(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isActivated', []);

        return parent::isActivated();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivated(bool $activated): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivated', [$activated]);

        return parent::setActivated($activated);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeBoost(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeBoost', []);

        return parent::getTypeBoost();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeBoost(string $typeBoost): \App\Entity\FormuleBoost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeBoost', [$typeBoost]);

        return parent::setTypeBoost($typeBoost);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbContactsMax(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbContactsMax', []);

        return parent::getNbContactsMax();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbContactsMax(?int $nbContactsMax): \App\Entity\FormuleBoost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbContactsMax', [$nbContactsMax]);

        return parent::setNbContactsMax($nbContactsMax);
    }

}
